import type { ReactNode } from "react";

export interface SimulationModeBadgeProps {
  /** Short label shown in the pill. Defaults to "Simulation Mode". */
  label?: string;
  /** Longer explanation rendered after the pill. */
  description?: ReactNode;
}

/**
 * Honesty banner for subsystems whose data comes from mocked or in-process
 * stand-ins rather than a real training/eval backend. Renders a yellow pill
 * plus an explanatory line so the user is never misled into believing the
 * numbers represent production runs.
 */
export function SimulationModeBadge({
  label = "Simulation Mode",
  description = "Data on this tab is generated by in-process stand-ins. Real training, evaluation, and deployment backends are not yet wired up — numbers are illustrative only.",
}: SimulationModeBadgeProps) {
  return (
    <div
      role="note"
      aria-label={label}
      style={{
        display: "flex",
        alignItems: "center",
        gap: "var(--space-2)",
        padding: "var(--space-2) var(--space-3)",
        margin: "var(--space-2) var(--space-3) 0 var(--space-3)",
        borderRadius: "var(--radius-sm)",
        border: "1px solid var(--warning-color)",
        background: "var(--warning-bg)",
        color: "var(--warning-color)",
        fontSize: "var(--font-size-xs)",
        lineHeight: 1.4,
      }}
    >
      <span
        style={{
          padding: "2px var(--space-2)",
          borderRadius: "var(--radius-xs-plus)",
          background: "var(--warning-color)",
          color: "var(--bg-primary)",
          fontWeight: 700,
          fontSize: "var(--font-size-xs)",
          letterSpacing: "0.04em",
          textTransform: "uppercase",
          flexShrink: 0,
        }}
      >
        {label}
      </span>
      <span style={{ color: "var(--text-secondary)" }}>{description}</span>
    </div>
  );
}

export default SimulationModeBadge;
