import type { ReactNode } from "react";

export interface SimulationModeBadgeProps {
  /** Short label shown in the pill. Defaults to "Simulation Mode". */
  label?: string;
  /** Longer explanation rendered after the pill. */
  description?: ReactNode;
  /**
   * Optional list of panel labels still showing illustrative data. When
   * provided, the badge appends "Still illustrative: …" so the user can
   * see exactly which sub-panels haven't been productionized. Pass an
   * empty array to render nothing (i.e. the surrounding tab is fully real).
   *
   * Slice productionization in `docs/design/rl-os/` shrinks this list
   * panel-by-panel as each slice ships.
   */
  covers?: string[];
}

/**
 * Honesty banner for subsystems whose data comes from mocked or in-process
 * stand-ins rather than a real training/eval backend. Renders a yellow pill
 * plus an explanatory line so the user is never misled into believing the
 * numbers represent production runs.
 */
export function SimulationModeBadge({
  label = "Simulation Mode",
  description = "Data on this tab is generated by in-process stand-ins. Real training, evaluation, and deployment backends are not yet wired up — numbers are illustrative only.",
  covers,
}: SimulationModeBadgeProps) {
  if (covers && covers.length === 0) return null;
  return (
    <div
      role="note"
      aria-label={label}
      style={{
        display: "flex",
        alignItems: "center",
        gap: "var(--space-2)",
        padding: "var(--space-2) var(--space-3)",
        margin: "var(--space-2) var(--space-3) 0 var(--space-3)",
        borderRadius: "var(--radius-sm)",
        border: "1px solid var(--warning-color)",
        background: "var(--warning-bg)",
        color: "var(--warning-color)",
        fontSize: "var(--font-size-xs)",
        lineHeight: 1.4,
      }}
    >
      <span
        style={{
          padding: "2px var(--space-2)",
          borderRadius: "var(--radius-xs-plus)",
          background: "var(--warning-color)",
          color: "var(--bg-primary)",
          fontWeight: 700,
          fontSize: "var(--font-size-xs)",
          letterSpacing: "0.04em",
          textTransform: "uppercase",
          flexShrink: 0,
        }}
      >
        {label}
      </span>
      <span style={{ color: "var(--text-secondary)" }}>
        {description}
        {covers && covers.length > 0 ? (
          <>
            {" "}
            <strong style={{ color: "var(--text-primary)" }}>Still illustrative:</strong>{" "}
            {covers.join(", ")}.
          </>
        ) : null}
      </span>
    </div>
  );
}

export default SimulationModeBadge;
