import type { LucideIcon } from "lucide-react";
import {
  MessageSquare, Bot, ClipboardList, Clock, Bookmark, Package,
  SlidersHorizontal, Anchor, ListChecks, Plug, Settings, Waves,
  Ruler, HardHat, Palette, Rocket, Database, Lock, GitBranch,
  Compass, Bug, Shield, TestTube, Users, BarChart3, Scale,
  Globe, Swords, DollarSign, Wrench, Cog, RefreshCw, Ship,
  Key, Flame, Container, Blocks, BookOpen, ArrowUpDown,
  ScrollText, Play, Notebook, TerminalSquare, Hammer,
  BookmarkCheck, GitFork, Scissors, Drama, Hexagon, TrendingUp,
  Zap, Network, UsersRound, BotMessageSquare, Activity, Store,
  ArrowLeftRight, Camera, Clapperboard, Eye, Cloud, ShieldCheck,
  Construction, HeartPulse, Cable, Paintbrush, FileText, Diff,
  PenTool, AlarmClock, Regex, KeyRound, Braces, Binary, Hash,
  Dices, Timer, Box, Workflow,
} from "lucide-react";

export interface TabMeta {
  icon: LucideIcon;
  label: string;
}

export const TAB_META: Record<string, TabMeta> = {
  chat:        { icon: MessageSquare,      label: "Chat" },
  agent:       { icon: Bot,                label: "Agent" },
  memory:      { icon: ClipboardList,      label: "Rules" },
  history:     { icon: Clock,              label: "History" },
  checkpoints: { icon: Bookmark,           label: "CPs" },
  artifacts:   { icon: Package,            label: "Artifacts" },
  manager:     { icon: SlidersHorizontal,  label: "Mgr" },
  hooks:       { icon: Anchor,             label: "Hooks" },
  jobs:        { icon: ListChecks,         label: "Jobs" },
  mcp:         { icon: Plug,               label: "MCP" },
  settings:    { icon: Settings,           label: "Keys" },
  cascade:     { icon: Waves,              label: "Flow" },
  specs:       { icon: Ruler,              label: "Specs" },
  workflow:    { icon: HardHat,            label: "Workflow" },
  design:      { icon: Palette,            label: "Design" },
  deploy:      { icon: Rocket,             label: "Deploy" },
  database:    { icon: Database,           label: "DB" },
  supabase:    { icon: Database,           label: "Supabase" },
  auth:        { icon: Lock,               label: "Auth" },
  github:      { icon: GitBranch,          label: "GH Sync" },
  steering:    { icon: Compass,            label: "Steering" },
  bugbot:      { icon: Bug,                label: "BugBot" },
  redteam:     { icon: Shield,             label: "RedTeam" },
  tests:       { icon: TestTube,           label: "Tests" },
  collab:      { icon: Users,              label: "Collab" },
  coverage:    { icon: BarChart3,          label: "Coverage" },
  compare:     { icon: Scale,              label: "Compare" },
  http:        { icon: Globe,              label: "HTTP" },
  arena:       { icon: Swords,             label: "Arena" },
  cost:        { icon: DollarSign,         label: "Cost" },
  autofix:     { icon: Wrench,             label: "Autofix" },
  processes:   { icon: Cog,                label: "Procs" },
  cicd:        { icon: RefreshCw,          label: "CI/CD" },
  k8s:         { icon: Ship,               label: "K8s" },
  env:         { icon: Key,                label: "Env" },
  profiler:    { icon: Flame,              label: "Profiler" },
  docker:      { icon: Container,          label: "Docker" },
  deps:        { icon: Blocks,             label: "Deps" },
  apidocs:     { icon: BookOpen,           label: "API Docs" },
  migrations:  { icon: ArrowUpDown,        label: "Migrations" },
  logs:        { icon: ScrollText,         label: "Logs" },
  scripts:     { icon: Play,               label: "Scripts" },
  notebook:    { icon: Notebook,           label: "Notebook" },
  ssh:         { icon: TerminalSquare,     label: "SSH" },
  utils:       { icon: Hammer,             label: "Utils" },
  markers:     { icon: BookmarkCheck,      label: "Markers" },
  bisect:      { icon: GitFork,            label: "Bisect" },
  snippets:    { icon: Scissors,           label: "Snippets" },
  mock:        { icon: Drama,              label: "Mock" },
  graphql:     { icon: Hexagon,            label: "GraphQL" },
  metrics:     { icon: TrendingUp,         label: "Metrics" },
  loadtest:    { icon: Zap,                label: "Load Test" },
  network:     { icon: Network,            label: "Network" },
  teams:       { icon: UsersRound,         label: "Teams" },
  cibot:       { icon: BotMessageSquare,   label: "CI Bot" },
  traces:      { icon: Activity,           label: "Traces" },
  marketplace: { icon: Store,              label: "Market" },
  transform:   { icon: ArrowLeftRight,     label: "Transform" },
  img2app:     { icon: Camera,             label: "Img2App" },
  recording:   { icon: Clapperboard,       label: "Recording" },
  visualtest:  { icon: Eye,                label: "Visual" },
  cloud:       { icon: Cloud,              label: "Cloud" },
  compliance:  { icon: ShieldCheck,        label: "Comply" },
  scaffold:    { icon: Construction,       label: "Scaffold" },
  health:      { icon: HeartPulse,         label: "Health" },
  websocket:   { icon: Cable,              label: "WS" },
  colors:      { icon: Paintbrush,         label: "Colors" },
  markdown:    { icon: FileText,           label: "Markdown" },
  difftool:    { icon: Diff,               label: "Diff" },
  canvas:      { icon: PenTool,            label: "Canvas" },
  cron:        { icon: AlarmClock,         label: "Cron" },
  regex:       { icon: Regex,              label: "Regex" },
  jwt:         { icon: KeyRound,           label: "JWT" },
  jsontools:   { icon: Braces,             label: "JSON" },
  encoding:    { icon: Binary,             label: "Encoding" },
  numbers:     { icon: Hash,               label: "Numbers" },
  datagen:     { icon: Dices,              label: "Data" },
  timestamp:   { icon: Timer,              label: "Time" },
  sandbox:     { icon: Box,                label: "Sandbox" },
  colorconv:   { icon: Palette,            label: "Color" },
  cidr:        { icon: Globe,              label: "CIDR" },
  csv:         { icon: FileText,           label: "CSV" },
  units:       { icon: Ruler,              label: "Units" },
  unicode:     { icon: Hash,               label: "Unicode" },
  dashboard:   { icon: BarChart3,           label: "Dashboard" },
};

export const DEFAULT_TAB_META: TabMeta = { icon: Workflow, label: "Flow" };
