tools:
    shell:
        allow:
            - find *
            - sort
            - grep *
            - head *
            - wc *
            - ls *
            - tail *
            - cd *
            - cargo check *
            - npx tsc *
            - cargo test *
