//! Session handoff documents — structured context transfer between sessions.
//!
//! Generates a WARRIOR-style 7-section handoff document from an agent session,
//! enabling smooth session continuity and context preservation.

use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

// ── Types ────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HandoffDocument {
    pub session_id: String,
    pub timestamp: String,
    pub sections: HandoffSections,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HandoffSections {
    /// What was accomplished in this session.
    pub work_done: Vec<String>,
    /// Assessment of current state — what's working, what's not.
    pub assessment: String,
    /// Files and resources that were referenced/modified.
    pub resources_used: Vec<String>,
    /// Next steps — what should be done next.
    pub readiness: Vec<String>,
    /// Known issues, blockers, or concerns.
    pub issues: Vec<String>,
    /// Risks, uncertainties, or things to watch out for.
    pub outlook: String,
    /// Key file paths, URLs, and other references.
    pub references: Vec<String>,
}

impl HandoffDocument {
    pub fn to_markdown(&self) -> String {
        let mut md = String::new();
        md.push_str(&format!(
            "# Session Handoff: {}\n\n**Timestamp:** {}\n\n---\n\n",
            self.session_id, self.timestamp
        ));

        md.push_str("## 1. Work Done\n\n");
        for item in &self.sections.work_done {
            md.push_str(&format!("- {}\n", item));
        }
        md.push('\n');

        md.push_str("## 2. Assessment\n\n");
        md.push_str(&self.sections.assessment);
        md.push_str("\n\n");

        md.push_str("## 3. Resources Used\n\n");
        for item in &self.sections.resources_used {
            md.push_str(&format!("- `{}`\n", item));
        }
        md.push('\n');

        md.push_str("## 4. Readiness (Next Steps)\n\n");
        for (i, item) in self.sections.readiness.iter().enumerate() {
            md.push_str(&format!("{}. {}\n", i + 1, item));
        }
        md.push('\n');

        md.push_str("## 5. Issues & Blockers\n\n");
        if self.sections.issues.is_empty() {
            md.push_str("None.\n");
        } else {
            for item in &self.sections.issues {
                md.push_str(&format!("- {}\n", item));
            }
        }
        md.push('\n');

        md.push_str("## 6. Outlook & Risks\n\n");
        md.push_str(&self.sections.outlook);
        md.push_str("\n\n");

        md.push_str("## 7. References\n\n");
        for item in &self.sections.references {
            md.push_str(&format!("- {}\n", item));
        }
        md.push('\n');

        md.push_str("---\n*Generated by VibeCLI Handoff*\n");
        md
    }

    pub fn from_agent_session(
        session_id: &str,
        steps: &[(String, String, bool)], // (tool, summary, success)
        files_changed: &[String],
        errors: &[String],
        summary: &str,
    ) -> Self {
        let work_done: Vec<String> = steps
            .iter()
            .filter(|(_, _, ok)| *ok)
            .map(|(tool, summary, _)| format!("{}: {}", tool, summary))
            .collect();

        let failed: Vec<_> = steps
            .iter()
            .filter(|(_, _, ok)| !*ok)
            .map(|(tool, summary, _)| format!("{}: {}", tool, summary))
            .collect();

        let assessment = if failed.is_empty() {
            format!("Session completed successfully. {}", summary)
        } else {
            format!(
                "Session completed with {} failure(s). {}",
                failed.len(),
                summary
            )
        };

        let mut issues: Vec<String> = errors.to_vec();
        issues.extend(failed);

        let readiness = vec![
            "Review generated changes".to_string(),
            "Run tests to validate modifications".to_string(),
            "Check git diff for unintended changes".to_string(),
        ];

        let references: Vec<String> = files_changed.to_vec();

        HandoffDocument {
            session_id: session_id.to_string(),
            timestamp: chrono_lite_now(),
            sections: HandoffSections {
                work_done,
                assessment,
                resources_used: files_changed.to_vec(),
                readiness,
                issues,
                outlook: "Monitor for regressions after applying changes.".to_string(),
                references,
            },
        }
    }
}

// ── Persistence ──────────────────────────────────────────────────────────────

pub struct HandoffStore {
    dir: PathBuf,
}

impl HandoffStore {
    pub fn new() -> Self {
        let dir = dirs_handoff_dir();
        Self { dir }
    }

    pub fn save(&self, doc: &HandoffDocument) -> Result<()> {
        std::fs::create_dir_all(&self.dir)?;
        let path = self.dir.join(format!("{}.md", doc.session_id));
        std::fs::write(&path, doc.to_markdown())?;

        // Also save JSON sidecar for machine parsing
        let json_path = self.dir.join(format!("{}.json", doc.session_id));
        let json = serde_json::to_string_pretty(doc)?;
        std::fs::write(&json_path, json)?;

        Ok(())
    }

    pub fn list(&self) -> Vec<String> {
        let mut ids = Vec::new();
        if let Ok(entries) = std::fs::read_dir(&self.dir) {
            for entry in entries.flatten() {
                let name = entry.file_name().to_string_lossy().to_string();
                if name.ends_with(".md") {
                    ids.push(name.trim_end_matches(".md").to_string());
                }
            }
        }
        ids.sort();
        ids
    }

    pub fn load(&self, session_id: &str) -> Result<HandoffDocument> {
        let json_path = self.dir.join(format!("{}.json", session_id));
        if json_path.exists() {
            let content = std::fs::read_to_string(&json_path)?;
            let doc: HandoffDocument = serde_json::from_str(&content)?;
            return Ok(doc);
        }
        anyhow::bail!("Handoff not found: {}", session_id)
    }

    pub fn load_markdown(&self, session_id: &str) -> Result<String> {
        let md_path = self.dir.join(format!("{}.md", session_id));
        if md_path.exists() {
            return Ok(std::fs::read_to_string(&md_path)?);
        }
        anyhow::bail!("Handoff not found: {}", session_id)
    }
}

fn dirs_handoff_dir() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
    PathBuf::from(home).join(".vibecli").join("handoffs")
}

fn chrono_lite_now() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let days = secs / 86400;
    let time_secs = secs % 86400;
    let hours = time_secs / 3600;
    let minutes = (time_secs % 3600) / 60;
    let seconds = time_secs % 60;
    let (year, month, day) = epoch_days_to_date(days);
    format!(
        "{:04}-{:02}-{:02}T{:02}:{:02}:{:02}Z",
        year, month, day, hours, minutes, seconds
    )
}

fn epoch_days_to_date(days: u64) -> (u64, u64, u64) {
    let z = days + 719468;
    let era = z / 146097;
    let doe = z - era * 146097;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    (y, m, d)
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_handoff() -> HandoffDocument {
        HandoffDocument::from_agent_session(
            "test-session-001",
            &[
                ("read_file".to_string(), "read src/main.rs".to_string(), true),
                ("write_file".to_string(), "write src/lib.rs".to_string(), true),
                ("bash".to_string(), "cargo test".to_string(), false),
            ],
            &["src/main.rs".to_string(), "src/lib.rs".to_string()],
            &["Build failed on line 42".to_string()],
            "Partial progress on feature",
        )
    }

    #[test]
    fn from_agent_session_basic() {
        let doc = sample_handoff();
        assert_eq!(doc.session_id, "test-session-001");
        assert_eq!(doc.sections.work_done.len(), 2); // 2 successful steps
        assert!(doc.sections.assessment.contains("1 failure"));
        assert_eq!(doc.sections.resources_used.len(), 2);
        assert!(doc.sections.issues.len() >= 1); // at least the error
    }

    #[test]
    fn to_markdown_has_seven_sections() {
        let doc = sample_handoff();
        let md = doc.to_markdown();
        assert!(md.contains("## 1. Work Done"));
        assert!(md.contains("## 2. Assessment"));
        assert!(md.contains("## 3. Resources Used"));
        assert!(md.contains("## 4. Readiness"));
        assert!(md.contains("## 5. Issues"));
        assert!(md.contains("## 6. Outlook"));
        assert!(md.contains("## 7. References"));
    }

    #[test]
    fn to_markdown_contains_session_id() {
        let doc = sample_handoff();
        let md = doc.to_markdown();
        assert!(md.contains("test-session-001"));
    }

    #[test]
    fn successful_session_assessment() {
        let doc = HandoffDocument::from_agent_session(
            "success-001",
            &[("read_file".to_string(), "read foo".to_string(), true)],
            &["foo.rs".to_string()],
            &[],
            "All good",
        );
        assert!(doc.sections.assessment.contains("successfully"));
        assert!(doc.sections.issues.is_empty());
    }

    #[test]
    fn handoff_serde_roundtrip() {
        let doc = sample_handoff();
        let json = serde_json::to_string(&doc).unwrap();
        let back: HandoffDocument = serde_json::from_str(&json).unwrap();
        assert_eq!(back.session_id, doc.session_id);
        assert_eq!(back.sections.work_done.len(), doc.sections.work_done.len());
    }

    #[test]
    fn store_list_empty() {
        let store = HandoffStore {
            dir: PathBuf::from("/tmp/vibecli_test_handoff_nonexistent"),
        };
        let ids = store.list();
        assert!(ids.is_empty());
    }
}
