//! Trust resolution for agent tool permissions and content sources.
//!
//! Claw-code parity Wave 4: resolves whether a file/URL/command can be
//! trusted based on provenance (local, git-tracked, remote, generated).

use serde::{Deserialize, Serialize};

// ─── Trust Level ──────────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum TrustLevel {
    /// System-level: CLAUDE.md, .claude/settings.json.
    System,
    /// Project-level: git-tracked files in the workspace.
    Project,
    /// User-granted: explicitly approved by the user.
    UserGranted,
    /// Untrusted: remote content, generated files, temp dirs.
    Untrusted,
}

impl std::fmt::Display for TrustLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::System      => write!(f, "system"),
            Self::Project     => write!(f, "project"),
            Self::UserGranted => write!(f, "user_granted"),
            Self::Untrusted   => write!(f, "untrusted"),
        }
    }
}

// ─── Content Source ───────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ContentSource {
    /// Local file at given path.
    LocalFile { path: String },
    /// URL (remote resource).
    RemoteUrl { url: String },
    /// Output of a shell command.
    CommandOutput { command: String },
    /// Content generated by the agent itself.
    AgentGenerated,
    /// Injected by the system (system prompt, CLAUDE.md).
    SystemInjected,
}

// ─── Trust Decision ───────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrustDecision {
    pub source: ContentSource,
    pub level: TrustLevel,
    pub reason: String,
    pub allow_execution: bool,
    pub allow_read: bool,
    pub allow_write: bool,
}

impl TrustDecision {
    pub fn is_trusted(&self) -> bool { self.level <= TrustLevel::Project }
}

// ─── Trust Resolver ───────────────────────────────────────────────────────────

pub struct TrustResolver {
    /// Workspace root directory.
    pub workspace_root: String,
    /// Explicitly granted paths/prefixes.
    pub granted_paths: Vec<String>,
    /// Denied paths (overrides grants).
    pub denied_paths: Vec<String>,
}

impl TrustResolver {
    pub fn new(workspace_root: impl Into<String>) -> Self {
        Self { workspace_root: workspace_root.into(), granted_paths: Vec::new(), denied_paths: Vec::new() }
    }

    pub fn grant_path(&mut self, path: impl Into<String>) { self.granted_paths.push(path.into()); }
    pub fn deny_path(&mut self, path: impl Into<String>) { self.denied_paths.push(path.into()); }

    pub fn resolve(&self, source: ContentSource) -> TrustDecision {
        match &source {
            ContentSource::SystemInjected => TrustDecision {
                source, level: TrustLevel::System, reason: "system prompt content".into(),
                allow_execution: true, allow_read: true, allow_write: true,
            },
            ContentSource::LocalFile { path } => {
                // Denied takes precedence
                if self.denied_paths.iter().any(|d| path.starts_with(d)) {
                    return TrustDecision {
                        source, level: TrustLevel::Untrusted,
                        reason: "path explicitly denied".into(),
                        allow_execution: false, allow_read: false, allow_write: false,
                    };
                }
                // Explicitly granted
                if self.granted_paths.iter().any(|g| path.starts_with(g)) {
                    return TrustDecision {
                        source, level: TrustLevel::UserGranted,
                        reason: "user-granted path".into(),
                        allow_execution: true, allow_read: true, allow_write: true,
                    };
                }
                // Inside workspace root
                if path.starts_with(&self.workspace_root) {
                    // System config files get System trust
                    if path.contains("CLAUDE.md") || path.contains(".claude/settings") {
                        return TrustDecision {
                            source, level: TrustLevel::System,
                            reason: "system configuration file".into(),
                            allow_execution: false, allow_read: true, allow_write: false,
                        };
                    }
                    return TrustDecision {
                        source, level: TrustLevel::Project,
                        reason: "file within workspace".into(),
                        allow_execution: false, allow_read: true, allow_write: true,
                    };
                }
                // Outside workspace
                TrustDecision {
                    source, level: TrustLevel::Untrusted,
                    reason: "file outside workspace".into(),
                    allow_execution: false, allow_read: true, allow_write: false,
                }
            }
            ContentSource::RemoteUrl { .. } => TrustDecision {
                source, level: TrustLevel::Untrusted, reason: "remote URL content".into(),
                allow_execution: false, allow_read: true, allow_write: false,
            },
            ContentSource::CommandOutput { .. } => TrustDecision {
                source, level: TrustLevel::Untrusted, reason: "command output not trusted for execution".into(),
                allow_execution: false, allow_read: true, allow_write: false,
            },
            ContentSource::AgentGenerated => TrustDecision {
                source, level: TrustLevel::Untrusted, reason: "agent-generated content requires review".into(),
                allow_execution: false, allow_read: true, allow_write: false,
            },
        }
    }

    /// Summarise trust level for a list of paths.
    pub fn min_trust_of(&self, paths: &[&str]) -> TrustLevel {
        paths.iter().map(|p| {
            self.resolve(ContentSource::LocalFile { path: p.to_string() }).level
        }).max().unwrap_or(TrustLevel::System)
    }
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn resolver() -> TrustResolver { TrustResolver::new("/workspace") }

    #[test]
    fn test_system_injected_trusted() {
        let r = resolver().resolve(ContentSource::SystemInjected);
        assert_eq!(r.level, TrustLevel::System);
        assert!(r.allow_execution);
    }

    #[test]
    fn test_workspace_file_project_trust() {
        let r = resolver().resolve(ContentSource::LocalFile { path: "/workspace/src/main.rs".into() });
        assert_eq!(r.level, TrustLevel::Project);
        assert!(r.allow_read);
        assert!(r.allow_write);
        assert!(!r.allow_execution);
    }

    #[test]
    fn test_claude_md_system_trust() {
        let r = resolver().resolve(ContentSource::LocalFile { path: "/workspace/CLAUDE.md".into() });
        assert_eq!(r.level, TrustLevel::System);
        assert!(!r.allow_write);
    }

    #[test]
    fn test_outside_workspace_untrusted() {
        let r = resolver().resolve(ContentSource::LocalFile { path: "/tmp/malicious.sh".into() });
        assert_eq!(r.level, TrustLevel::Untrusted);
        assert!(!r.allow_execution);
        assert!(!r.allow_write);
    }

    #[test]
    fn test_remote_url_untrusted() {
        let r = resolver().resolve(ContentSource::RemoteUrl { url: "https://example.com/script.sh".into() });
        assert_eq!(r.level, TrustLevel::Untrusted);
        assert!(!r.allow_execution);
    }

    #[test]
    fn test_command_output_untrusted() {
        let r = resolver().resolve(ContentSource::CommandOutput { command: "curl evil.sh".into() });
        assert_eq!(r.level, TrustLevel::Untrusted);
        assert!(!r.allow_execution);
    }

    #[test]
    fn test_agent_generated_untrusted() {
        let r = resolver().resolve(ContentSource::AgentGenerated);
        assert_eq!(r.level, TrustLevel::Untrusted);
    }

    #[test]
    fn test_granted_path_user_trust() {
        let mut res = resolver();
        res.grant_path("/tmp/approved");
        let r = res.resolve(ContentSource::LocalFile { path: "/tmp/approved/file.rs".into() });
        assert_eq!(r.level, TrustLevel::UserGranted);
    }

    #[test]
    fn test_denied_path_overrides_workspace() {
        let mut res = resolver();
        res.deny_path("/workspace/dist");
        let r = res.resolve(ContentSource::LocalFile { path: "/workspace/dist/bundle.js".into() });
        assert_eq!(r.level, TrustLevel::Untrusted);
    }

    #[test]
    fn test_denied_overrides_grant() {
        let mut res = resolver();
        res.grant_path("/workspace/dist");
        res.deny_path("/workspace/dist");
        let r = res.resolve(ContentSource::LocalFile { path: "/workspace/dist/x.js".into() });
        assert_eq!(r.level, TrustLevel::Untrusted);
    }

    #[test]
    fn test_is_trusted_project() {
        let r = TrustDecision {
            source: ContentSource::AgentGenerated, level: TrustLevel::Project,
            reason: "".into(), allow_execution: false, allow_read: true, allow_write: true,
        };
        assert!(r.is_trusted());
    }

    #[test]
    fn test_is_trusted_false_for_untrusted() {
        let r = TrustDecision {
            source: ContentSource::AgentGenerated, level: TrustLevel::Untrusted,
            reason: "".into(), allow_execution: false, allow_read: true, allow_write: false,
        };
        assert!(!r.is_trusted());
    }

    #[test]
    fn test_min_trust_of_returns_least_trusted() {
        let res = resolver();
        let t = res.min_trust_of(&["/workspace/src/lib.rs", "/tmp/outside.rs"]);
        assert_eq!(t, TrustLevel::Untrusted);
    }

    #[test]
    fn test_trust_level_ordering() {
        assert!(TrustLevel::System < TrustLevel::Untrusted);
        assert!(TrustLevel::Project < TrustLevel::Untrusted);
    }

    #[test]
    fn test_trust_level_display() {
        assert_eq!(TrustLevel::System.to_string(), "system");
        assert_eq!(TrustLevel::Untrusted.to_string(), "untrusted");
    }
}
