//! Structured verification checklist — 10-category quality gate.
//!
//! Inspired by fire-flow's 70-point verification, this module evaluates a
//! workspace across Code Quality, Testing, Security, Performance, Documentation,
//! Database, API Design, Infrastructure, Version Control, and Accessibility.

use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::path::Path;
use std::sync::Arc;
use vibe_ai::provider::AIProvider;
use vibe_ai::provider::{Message, MessageRole};

// ── Types ────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VerificationCategory {
    CodeQuality,
    Testing,
    Security,
    Performance,
    Documentation,
    Database,
    ApiDesign,
    Infrastructure,
    VersionControl,
    Accessibility,
}

impl VerificationCategory {
    pub const ALL: &'static [Self] = &[
        Self::CodeQuality,
        Self::Testing,
        Self::Security,
        Self::Performance,
        Self::Documentation,
        Self::Database,
        Self::ApiDesign,
        Self::Infrastructure,
        Self::VersionControl,
        Self::Accessibility,
    ];
}

impl std::fmt::Display for VerificationCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::CodeQuality => write!(f, "Code Quality"),
            Self::Testing => write!(f, "Testing"),
            Self::Security => write!(f, "Security"),
            Self::Performance => write!(f, "Performance"),
            Self::Documentation => write!(f, "Documentation"),
            Self::Database => write!(f, "Database"),
            Self::ApiDesign => write!(f, "API Design"),
            Self::Infrastructure => write!(f, "Infrastructure"),
            Self::VersionControl => write!(f, "Version Control"),
            Self::Accessibility => write!(f, "Accessibility"),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CheckStatus {
    Pass,
    Fail,
    Skip,
    NotApplicable,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationCheck {
    pub category: VerificationCategory,
    pub name: String,
    pub description: String,
    pub status: CheckStatus,
    pub evidence: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationReport {
    pub checks: Vec<VerificationCheck>,
    pub score: f32,
    pub pass_rate: f32,
    pub timestamp: String,
    pub categories_summary: Vec<CategorySummary>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CategorySummary {
    pub category: VerificationCategory,
    pub pass: usize,
    pub fail: usize,
    pub skip: usize,
    pub na: usize,
    pub score: f32,
}

impl VerificationReport {
    pub fn to_markdown(&self) -> String {
        let mut md = String::new();
        md.push_str("# Verification Report\n\n");
        md.push_str(&format!(
            "**Score:** {:.1}% | **Pass rate:** {:.1}% | **Timestamp:** {}\n\n",
            self.score, self.pass_rate, self.timestamp
        ));

        md.push_str("## Category Summary\n\n");
        md.push_str("| Category | Pass | Fail | Skip | N/A | Score |\n");
        md.push_str("|----------|------|------|------|-----|-------|\n");
        for cs in &self.categories_summary {
            let icon = if cs.fail == 0 { "✅" } else { "⚠️" };
            md.push_str(&format!(
                "| {} {} | {} | {} | {} | {} | {:.0}% |\n",
                icon, cs.category, cs.pass, cs.fail, cs.skip, cs.na, cs.score
            ));
        }
        md.push('\n');

        // Group checks by category
        for cat in VerificationCategory::ALL {
            let checks: Vec<_> = self.checks.iter().filter(|c| c.category == *cat).collect();
            if checks.is_empty() {
                continue;
            }
            md.push_str(&format!("## {}\n\n", cat));
            for check in &checks {
                let icon = match check.status {
                    CheckStatus::Pass => "✅",
                    CheckStatus::Fail => "❌",
                    CheckStatus::Skip => "⏭️",
                    CheckStatus::NotApplicable => "➖",
                };
                md.push_str(&format!("- {} **{}**: {}\n", icon, check.name, check.description));
                if !check.evidence.is_empty() {
                    md.push_str(&format!("  - Evidence: {}\n", check.evidence));
                }
            }
            md.push('\n');
        }

        md.push_str("---\n*Generated by VibeCLI Verification*\n");
        md
    }
}

// ── Prompts ──────────────────────────────────────────────────────────────────

pub fn stage_checklist_prompt(category: VerificationCategory, workspace_info: &str) -> String {
    let checks = match category {
        VerificationCategory::CodeQuality => vec![
            "No compiler warnings or errors",
            "Consistent naming conventions",
            "No dead code or unused imports",
            "Functions are reasonably sized (<50 lines)",
            "Error handling is consistent",
            "No hardcoded magic numbers",
            "Code follows DRY principle",
        ],
        VerificationCategory::Testing => vec![
            "Unit tests exist for core logic",
            "Tests are passing",
            "Edge cases are covered",
            "No flaky tests",
            "Test coverage is adequate (>60%)",
            "Integration tests exist where needed",
            "Mocks are used appropriately",
        ],
        VerificationCategory::Security => vec![
            "No hardcoded secrets or API keys",
            "Input validation at boundaries",
            "No SQL injection vulnerabilities",
            "No XSS vulnerabilities",
            "Authentication/authorization checks",
            "Sensitive data is encrypted/redacted",
            "Dependencies have no known CVEs",
        ],
        VerificationCategory::Performance => vec![
            "No N+1 query patterns",
            "Large data sets use pagination",
            "Caching is used where appropriate",
            "No unnecessary allocations in hot paths",
            "Async operations are non-blocking",
            "Database queries are indexed",
            "Resource cleanup (files, connections)",
        ],
        VerificationCategory::Documentation => vec![
            "Public API has documentation",
            "README is up to date",
            "Complex logic has inline comments",
            "Configuration is documented",
            "Breaking changes are noted",
            "Examples are provided",
            "Architecture decisions are recorded",
        ],
        VerificationCategory::Database => vec![
            "Migrations are reversible",
            "Schema changes are backward-compatible",
            "Indexes exist for common queries",
            "Foreign keys maintain referential integrity",
            "No data loss in migrations",
            "Connection pooling is configured",
            "Transactions are used for multi-step ops",
        ],
        VerificationCategory::ApiDesign => vec![
            "RESTful conventions followed",
            "Error responses are consistent",
            "Versioning strategy exists",
            "Rate limiting is implemented",
            "Input validation on all endpoints",
            "Response schemas are documented",
            "Pagination for list endpoints",
        ],
        VerificationCategory::Infrastructure => vec![
            "CI/CD pipeline is configured",
            "Environment variables are documented",
            "Health checks are implemented",
            "Logging is structured",
            "Monitoring/alerting is set up",
            "Deployment is automated",
            "Rollback procedure exists",
        ],
        VerificationCategory::VersionControl => vec![
            "Commits are atomic and well-described",
            "Branch naming follows convention",
            "No large binary files committed",
            "Gitignore covers build artifacts",
            "No merge conflicts remain",
            "Feature branches are up to date",
            "Tags follow semantic versioning",
        ],
        VerificationCategory::Accessibility => vec![
            "ARIA attributes on interactive elements",
            "Keyboard navigation works",
            "Color contrast meets WCAG AA",
            "Screen reader compatibility",
            "Focus management is correct",
            "Alt text on images",
            "Form labels are associated",
        ],
    };

    format!(
        r#"You are a verification auditor. Evaluate the following workspace against the "{}" checklist.

Workspace info:
{}

Checks to evaluate:
{}

Respond with ONLY valid JSON (no markdown fences):
{{
  "checks": [
    {{
      "name": "check name",
      "status": "pass|fail|skip|not_applicable",
      "evidence": "brief evidence or reason"
    }}
  ]
}}

Evaluate each check honestly. Use "skip" if you can't determine the answer from available information. Use "not_applicable" if the check doesn't apply to this project."#,
        category,
        workspace_info,
        checks
            .iter()
            .enumerate()
            .map(|(i, c)| format!("{}. {}", i + 1, c))
            .collect::<Vec<_>>()
            .join("\n")
    )
}

// ── Runner ───────────────────────────────────────────────────────────────────

pub async fn run_verification(
    workspace: &Path,
    categories: &[VerificationCategory],
    llm: Arc<dyn AIProvider>,
) -> Result<VerificationReport> {
    // Gather workspace info
    let workspace_info = gather_workspace_info(workspace);

    let mut all_checks: Vec<VerificationCheck> = Vec::new();

    for cat in categories {
        let prompt = stage_checklist_prompt(*cat, &workspace_info);
        let messages = vec![
            Message {
                role: MessageRole::System,
                content: "You are a code verification auditor. Respond only with valid JSON.".to_string(),
            },
            Message {
                role: MessageRole::User,
                content: prompt,
            },
        ];

        match llm.chat(&messages, None).await {
            Ok(response) => {
                let checks = parse_checklist_response(&response, *cat);
                all_checks.extend(checks);
            }
            Err(e) => {
                tracing::warn!(category = %cat, error = %e, "Failed to verify category");
                all_checks.push(VerificationCheck {
                    category: *cat,
                    name: "Verification".to_string(),
                    description: format!("Failed to evaluate: {}", e),
                    status: CheckStatus::Skip,
                    evidence: String::new(),
                });
            }
        }
    }

    // Compute scores
    let (total_pass, total_applicable) = all_checks.iter().fold((0usize, 0usize), |(p, a), c| {
        match c.status {
            CheckStatus::Pass => (p + 1, a + 1),
            CheckStatus::Fail => (p, a + 1),
            _ => (p, a),
        }
    });

    let pass_rate = if total_applicable > 0 {
        (total_pass as f32 / total_applicable as f32) * 100.0
    } else {
        100.0
    };

    let categories_summary: Vec<CategorySummary> = categories
        .iter()
        .map(|cat| {
            let cat_checks: Vec<_> = all_checks.iter().filter(|c| c.category == *cat).collect();
            let pass = cat_checks.iter().filter(|c| c.status == CheckStatus::Pass).count();
            let fail = cat_checks.iter().filter(|c| c.status == CheckStatus::Fail).count();
            let skip = cat_checks.iter().filter(|c| c.status == CheckStatus::Skip).count();
            let na = cat_checks.iter().filter(|c| c.status == CheckStatus::NotApplicable).count();
            let applicable = pass + fail;
            let cat_score = if applicable > 0 {
                (pass as f32 / applicable as f32) * 100.0
            } else {
                100.0
            };
            CategorySummary {
                category: *cat,
                pass,
                fail,
                skip,
                na,
                score: cat_score,
            }
        })
        .collect();

    let timestamp = chrono_lite_now();

    Ok(VerificationReport {
        checks: all_checks,
        score: pass_rate,
        pass_rate,
        timestamp,
        categories_summary,
    })
}

// ── Helpers ──────────────────────────────────────────────────────────────────

fn gather_workspace_info(workspace: &Path) -> String {
    let mut info = String::new();

    // Check for common project files
    let markers = [
        ("Cargo.toml", "Rust"),
        ("package.json", "JavaScript/TypeScript"),
        ("go.mod", "Go"),
        ("pyproject.toml", "Python"),
        ("requirements.txt", "Python"),
        ("Gemfile", "Ruby"),
    ];

    for (file, lang) in &markers {
        if workspace.join(file).exists() {
            info.push_str(&format!("- {} project detected ({})\n", lang, file));
        }
    }

    // Check for CI
    let ci_markers = [
        (".github/workflows", "GitHub Actions"),
        (".gitlab-ci.yml", "GitLab CI"),
        ("Jenkinsfile", "Jenkins"),
    ];
    for (path, ci) in &ci_markers {
        if workspace.join(path).exists() {
            info.push_str(&format!("- CI: {} ({})\n", ci, path));
        }
    }

    // Check for tests directory
    if workspace.join("tests").exists() || workspace.join("test").exists() {
        info.push_str("- Test directory exists\n");
    }

    // Check for docs
    if workspace.join("docs").exists() || workspace.join("README.md").exists() {
        info.push_str("- Documentation exists\n");
    }

    if info.is_empty() {
        info.push_str("(No project markers detected)\n");
    }

    info
}

pub fn parse_checklist_response(response: &str, category: VerificationCategory) -> Vec<VerificationCheck> {
    let raw = response.trim();
    let json_str = if raw.starts_with("```") {
        raw.lines()
            .filter(|l| !l.starts_with("```"))
            .collect::<Vec<_>>()
            .join("\n")
    } else {
        raw.to_string()
    };

    #[derive(Deserialize)]
    struct RawResponse {
        #[serde(default)]
        checks: Vec<RawCheck>,
    }

    #[derive(Deserialize)]
    struct RawCheck {
        #[serde(default)]
        name: String,
        #[serde(default)]
        status: String,
        #[serde(default)]
        evidence: String,
    }

    let parsed: RawResponse = serde_json::from_str(&json_str)
        .unwrap_or(RawResponse { checks: vec![] });

    parsed
        .checks
        .into_iter()
        .map(|c| VerificationCheck {
            category,
            name: c.name.clone(),
            description: c.name,
            status: match c.status.as_str() {
                "pass" => CheckStatus::Pass,
                "fail" => CheckStatus::Fail,
                "skip" => CheckStatus::Skip,
                "not_applicable" => CheckStatus::NotApplicable,
                _ => CheckStatus::Skip,
            },
            evidence: c.evidence,
        })
        .collect()
}

fn chrono_lite_now() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    // Simple ISO-ish timestamp without chrono dependency
    let days = secs / 86400;
    let time_secs = secs % 86400;
    let hours = time_secs / 3600;
    let minutes = (time_secs % 3600) / 60;
    let seconds = time_secs % 60;
    // Approximate date from epoch days
    let (year, month, day) = epoch_days_to_date(days);
    format!(
        "{:04}-{:02}-{:02}T{:02}:{:02}:{:02}Z",
        year, month, day, hours, minutes, seconds
    )
}

fn epoch_days_to_date(days: u64) -> (u64, u64, u64) {
    // Civil date from epoch day (algorithm from Howard Hinnant)
    let z = days + 719468;
    let era = z / 146097;
    let doe = z - era * 146097;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    (y, m, d)
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn category_display() {
        assert_eq!(format!("{}", VerificationCategory::CodeQuality), "Code Quality");
        assert_eq!(format!("{}", VerificationCategory::ApiDesign), "API Design");
        assert_eq!(format!("{}", VerificationCategory::VersionControl), "Version Control");
    }

    #[test]
    fn all_categories_has_ten() {
        assert_eq!(VerificationCategory::ALL.len(), 10);
    }

    #[test]
    fn parse_checklist_response_valid_json() {
        let json = r#"{"checks": [
            {"name": "No warnings", "status": "pass", "evidence": "cargo check clean"},
            {"name": "Dead code", "status": "fail", "evidence": "unused function found"}
        ]}"#;
        let checks = parse_checklist_response(json, VerificationCategory::CodeQuality);
        assert_eq!(checks.len(), 2);
        assert_eq!(checks[0].status, CheckStatus::Pass);
        assert_eq!(checks[1].status, CheckStatus::Fail);
        assert_eq!(checks[0].category, VerificationCategory::CodeQuality);
    }

    #[test]
    fn parse_checklist_response_with_fences() {
        let json = "```json\n{\"checks\": [{\"name\": \"test\", \"status\": \"pass\", \"evidence\": \"ok\"}]}\n```";
        let checks = parse_checklist_response(json, VerificationCategory::Testing);
        assert_eq!(checks.len(), 1);
        assert_eq!(checks[0].status, CheckStatus::Pass);
    }

    #[test]
    fn parse_checklist_response_invalid_json() {
        let checks = parse_checklist_response("not json", VerificationCategory::Security);
        assert!(checks.is_empty());
    }

    #[test]
    fn parse_checklist_unknown_status() {
        let json = r#"{"checks": [{"name": "x", "status": "unknown", "evidence": ""}]}"#;
        let checks = parse_checklist_response(json, VerificationCategory::Performance);
        assert_eq!(checks[0].status, CheckStatus::Skip);
    }

    #[test]
    fn report_to_markdown_contains_sections() {
        let report = VerificationReport {
            checks: vec![
                VerificationCheck {
                    category: VerificationCategory::CodeQuality,
                    name: "No warnings".to_string(),
                    description: "No warnings".to_string(),
                    status: CheckStatus::Pass,
                    evidence: "clean build".to_string(),
                },
                VerificationCheck {
                    category: VerificationCategory::Security,
                    name: "No secrets".to_string(),
                    description: "No secrets".to_string(),
                    status: CheckStatus::Fail,
                    evidence: "API key found".to_string(),
                },
            ],
            score: 50.0,
            pass_rate: 50.0,
            timestamp: "2026-03-06T00:00:00Z".to_string(),
            categories_summary: vec![
                CategorySummary {
                    category: VerificationCategory::CodeQuality,
                    pass: 1, fail: 0, skip: 0, na: 0, score: 100.0,
                },
                CategorySummary {
                    category: VerificationCategory::Security,
                    pass: 0, fail: 1, skip: 0, na: 0, score: 0.0,
                },
            ],
        };
        let md = report.to_markdown();
        assert!(md.contains("# Verification Report"));
        assert!(md.contains("50.0%"));
        assert!(md.contains("Code Quality"));
        assert!(md.contains("Security"));
        assert!(md.contains("No warnings"));
        assert!(md.contains("API key found"));
    }

    #[test]
    fn stage_checklist_prompt_has_category_name() {
        let prompt = stage_checklist_prompt(VerificationCategory::Testing, "Rust project");
        assert!(prompt.contains("Testing"));
        assert!(prompt.contains("Rust project"));
        assert!(prompt.contains("Unit tests"));
    }

    #[test]
    fn epoch_days_to_date_known_date() {
        // 2024-01-01 = 19723 days since epoch
        let (y, m, d) = epoch_days_to_date(19723);
        assert_eq!(y, 2024);
        assert_eq!(m, 1);
        assert_eq!(d, 1);
    }

    #[test]
    fn gather_workspace_info_nonexistent_path() {
        let info = gather_workspace_info(Path::new("/tmp/nonexistent_vibecli_test_dir"));
        assert!(info.contains("No project markers"));
    }

    // ── Additional tests ──────────────────────────────────────────────────

    #[test]
    fn category_display_all_ten() {
        let displays: Vec<String> = VerificationCategory::ALL.iter().map(|c| format!("{}", c)).collect();
        assert_eq!(displays.len(), 10);
        assert!(displays.contains(&"Testing".to_string()));
        assert!(displays.contains(&"Security".to_string()));
        assert!(displays.contains(&"Performance".to_string()));
        assert!(displays.contains(&"Documentation".to_string()));
        assert!(displays.contains(&"Database".to_string()));
        assert!(displays.contains(&"Infrastructure".to_string()));
        assert!(displays.contains(&"Accessibility".to_string()));
    }

    #[test]
    fn check_status_serde_roundtrip() {
        for status in [CheckStatus::Pass, CheckStatus::Fail, CheckStatus::Skip, CheckStatus::NotApplicable] {
            let json = serde_json::to_string(&status).unwrap();
            let back: CheckStatus = serde_json::from_str(&json).unwrap();
            assert_eq!(back, status);
        }
    }

    #[test]
    fn verification_check_serde_roundtrip() {
        let check = VerificationCheck {
            category: VerificationCategory::Security,
            name: "No secrets".to_string(),
            description: "Check for hardcoded secrets".to_string(),
            status: CheckStatus::Pass,
            evidence: "No secrets found".to_string(),
        };
        let json = serde_json::to_string(&check).unwrap();
        let back: VerificationCheck = serde_json::from_str(&json).unwrap();
        assert_eq!(back.category, VerificationCategory::Security);
        assert_eq!(back.status, CheckStatus::Pass);
        assert_eq!(back.name, "No secrets");
    }

    #[test]
    fn parse_checklist_response_not_applicable_status() {
        let json = r#"{"checks": [{"name": "N/A check", "status": "not_applicable", "evidence": "not relevant"}]}"#;
        let checks = parse_checklist_response(json, VerificationCategory::Database);
        assert_eq!(checks.len(), 1);
        assert_eq!(checks[0].status, CheckStatus::NotApplicable);
        assert_eq!(checks[0].category, VerificationCategory::Database);
    }

    #[test]
    fn parse_checklist_response_empty_checks_array() {
        let json = r#"{"checks": []}"#;
        let checks = parse_checklist_response(json, VerificationCategory::Testing);
        assert!(checks.is_empty());
    }

    #[test]
    fn parse_checklist_response_missing_fields_default() {
        let json = r#"{"checks": [{}]}"#;
        let checks = parse_checklist_response(json, VerificationCategory::CodeQuality);
        assert_eq!(checks.len(), 1);
        assert_eq!(checks[0].name, "");
        assert_eq!(checks[0].status, CheckStatus::Skip); // unknown status defaults to Skip
        assert_eq!(checks[0].evidence, "");
    }

    #[test]
    fn report_to_markdown_empty_checks() {
        let report = VerificationReport {
            checks: vec![],
            score: 100.0,
            pass_rate: 100.0,
            timestamp: "2026-03-08T00:00:00Z".to_string(),
            categories_summary: vec![],
        };
        let md = report.to_markdown();
        assert!(md.contains("# Verification Report"));
        assert!(md.contains("100.0%"));
        assert!(md.contains("Generated by VibeCLI Verification"));
    }

    #[test]
    fn stage_checklist_prompt_all_categories_have_checks() {
        for cat in VerificationCategory::ALL {
            let prompt = stage_checklist_prompt(*cat, "test workspace");
            assert!(prompt.contains("1."), "Category {:?} should have numbered checks", cat);
            assert!(prompt.contains("test workspace"));
        }
    }

    #[test]
    fn epoch_days_to_date_unix_epoch() {
        let (y, m, d) = epoch_days_to_date(0);
        assert_eq!(y, 1970);
        assert_eq!(m, 1);
        assert_eq!(d, 1);
    }

    #[test]
    fn category_summary_serde_roundtrip() {
        let summary = CategorySummary {
            category: VerificationCategory::Performance,
            pass: 5,
            fail: 2,
            skip: 1,
            na: 0,
            score: 71.4,
        };
        let json = serde_json::to_string(&summary).unwrap();
        let back: CategorySummary = serde_json::from_str(&json).unwrap();
        assert_eq!(back.category, VerificationCategory::Performance);
        assert_eq!(back.pass, 5);
        assert_eq!(back.fail, 2);
    }

    #[test]
    fn verification_category_serde_roundtrip() {
        for cat in VerificationCategory::ALL {
            let json = serde_json::to_string(cat).unwrap();
            let back: VerificationCategory = serde_json::from_str(&json).unwrap();
            assert_eq!(&back, cat);
        }
    }
}
