//! watch_auth.rs — Apple Watch device registration, JWT issuance/verification,
//! and wrist-detection-aware session locking.
//!
//! Security model:
//!  • Registration: Watch generates P256 keypair (Apple Secure Enclave — only
//!    P256/secp256r1 ECDSA is supported, not Ed25519), signs a daemon-issued
//!    nonce, proves possession without sending private key.
//!  • Public key format: 64-byte uncompressed X9.62 (Swift rawRepresentation,
//!    i.e. the 64-byte x||y without the 0x04 prefix byte).
//!  • Signature format: 64-byte compact IEEE P1363 (r||s, 32 bytes each).
//!  • Tokens: short-lived JWTs (15 min) signed with HMAC-SHA256 using a secret
//!    stored in ProfileStore. Refresh tokens (7 days) signed by watch's Secure
//!    Enclave private key — daemon verifies with stored public key.
//!  • Wrist-off: daemon marks device suspended; further requests return 423 Locked
//!    until the watch re-authenticates with biometrics.
//!  • Revocation: any token issued before `revoked_at` is rejected instantly.

use anyhow::{bail, Result};
use base64::{engine::general_purpose::URL_SAFE_NO_PAD as B64, Engine};
use hmac::{Hmac, Mac};
use rand::Rng;
use serde::{Deserialize, Serialize};
use sha2::Sha256;
use std::time::{SystemTime, UNIX_EPOCH};

type HmacSha256 = Hmac<Sha256>;

// ── Constants ─────────────────────────────────────────────────────────────────

pub const ACCESS_TOKEN_TTL_SECS: u64 = 900; // 15 minutes
pub const REFRESH_TOKEN_TTL_SECS: u64 = 604_800; // 7 days
pub const NONCE_TTL_SECS: u64 = 120; // registration nonce valid 2 minutes
pub const MAX_WATCH_DEVICES: usize = 10;

// ── Stored device record ───────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WatchDevice {
    /// Opaque 128-bit hex device ID generated by the Watch
    pub device_id: String,
    /// Human-readable name (e.g. "Ravindra's Apple Watch Ultra")
    pub name: String,
    /// Base64url-encoded Ed25519 public key from Watch Secure Enclave
    pub public_key_b64: String,
    /// watchOS version string
    pub os_version: String,
    /// Watch model identifier (e.g. "Watch7,1")
    pub model: String,
    /// Unix timestamp of registration
    pub registered_at: u64,
    /// Unix timestamp of last successful auth (updated on token refresh)
    pub last_seen: u64,
    /// If set, all tokens issued before this time are invalid (post-revoke)
    pub revoked_at: Option<u64>,
    /// True when watch reports wrist-off; blocks new requests until re-auth
    pub wrist_suspended: bool,
}

// ── JWT claims ─────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WatchClaims {
    /// Subject: device_id
    pub sub: String,
    /// Issued at (Unix)
    pub iat: u64,
    /// Expiry (Unix)
    pub exp: u64,
    /// JWT ID (nonce — prevents replay within TTL window)
    pub jti: String,
    /// Machine ID this token is bound to
    pub machine_id: String,
    /// Token kind: "access" or "refresh"
    pub kind: String,
}

// ── Registration challenge/response ──────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize)]
pub struct RegistrationChallenge {
    pub nonce: String, // 128-bit hex, single-use
    pub machine_id: String,
    pub issued_at: u64,
    pub expires_at: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WatchRegisterRequest {
    pub device_id: String,
    pub name: String,
    pub os_version: String,
    pub model: String,
    /// Base64url Ed25519 public key
    pub public_key_b64: String,
    /// Base64url Ed25519 signature over SHA-256(nonce || device_id || issued_at)
    pub signature_b64: String,
    /// The nonce from the challenge
    pub nonce: String,
    /// Apple DeviceCheck token (optional; validated server-side when present)
    pub device_check_token: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct WatchRegisterResponse {
    pub access_token: String,
    pub refresh_token: String,
    pub expires_in: u64,
    pub device_id: String,
}

// ── Token refresh ─────────────────────────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize)]
pub struct WatchRefreshRequest {
    pub device_id: String,
    /// Existing refresh token (HMAC-JWT)
    pub refresh_token: String,
    /// Ed25519 signature over SHA-256(refresh_token || timestamp) to prove key
    /// possession alongside the token, preventing token-only theft attacks.
    pub proof_signature_b64: String,
    pub timestamp: u64,
}

// ── Wrist event ───────────────────────────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize)]
pub struct WristEvent {
    pub device_id: String,
    pub on_wrist: bool,
    pub timestamp: u64,
    /// Ed25519 signature over SHA-256(device_id || on_wrist_byte || timestamp)
    pub signature_b64: String,
}

// ── WatchAuthManager ─────────────────────────────────────────────────────────

#[derive(Debug)]
pub struct WatchAuthManager {
    machine_id: String,
    jwt_secret: Vec<u8>, // 32-byte HMAC-SHA256 key
    /// Pending registration nonces: nonce_hex → (issued_at, device_id hint)
    pending_nonces: std::collections::HashMap<String, (u64, String)>,
}

impl WatchAuthManager {
    /// Load or generate the JWT signing secret from ProfileStore.
    /// Testing constructor — bypasses ProfileStore, uses supplied key material.
    pub fn new_with_path(_path: &std::path::Path, secret: &[u8]) -> Result<Self> {
        Ok(Self {
            machine_id: "test-machine-bdd".into(),
            jwt_secret: secret.to_vec(),
            pending_nonces: Default::default(),
        })
    }

    pub fn new(machine_id: impl Into<String>) -> Result<Self> {
        let machine_id = machine_id.into();
        let store = crate::profile_store::ProfileStore::new()
            .map_err(|e| anyhow::anyhow!("{}", e))?;
        let secret = match store.get_api_key("default", "watch.jwt_secret").ok().flatten() {
            Some(s) if !s.is_empty() => hex::decode(&s)?,
            _ => {
                let bytes: Vec<u8> = rand::thread_rng().gen::<[u8; 32]>().to_vec();
                store.set_api_key("default", "watch.jwt_secret", &hex::encode(&bytes))
                    .map_err(|e| anyhow::anyhow!("{}", e))?;
                bytes
            }
        };
        Ok(Self { machine_id, jwt_secret: secret, pending_nonces: Default::default() })
    }

    // ── Challenge generation ───────────────────────────────────────────────

    /// Generate a single-use registration nonce.  Returns the challenge JSON.
    pub fn issue_challenge(&mut self) -> Result<RegistrationChallenge> {
        let nonce: String = format!("{:032x}", rand::thread_rng().gen::<u128>());
        let now = now_unix();
        let expires_at = now + NONCE_TTL_SECS;
        self.pending_nonces.insert(nonce.clone(), (now, String::new()));
        // Prune expired nonces
        self.pending_nonces.retain(|_, (iat, _)| now - *iat < NONCE_TTL_SECS + 10);
        Ok(RegistrationChallenge {
            nonce,
            machine_id: self.machine_id.clone(),
            issued_at: now,
            expires_at,
        })
    }

    // ── Registration ──────────────────────────────────────────────────────

    pub fn register_device(&mut self, req: &WatchRegisterRequest) -> Result<WatchDevice> {
        // 1. Validate nonce is pending and not expired
        let now = now_unix();
        let (issued_at, _) = self
            .pending_nonces
            .remove(&req.nonce)
            .ok_or_else(|| anyhow::anyhow!("Unknown or already-used nonce"))?;
        if now - issued_at > NONCE_TTL_SECS {
            bail!("Registration nonce expired");
        }

        // 2. Decode public key (64-byte P256 raw: x||y, Swift rawRepresentation)
        let pk_bytes = B64.decode(&req.public_key_b64)?;
        if pk_bytes.len() != 64 {
            bail!("Invalid P256 public key length (expected 64 bytes, got {})", pk_bytes.len());
        }

        // 3. Verify P256 ECDSA signature over SHA-256(nonce || device_id || issued_at_be)
        //    Signature is 64-byte compact IEEE P1363 (r||s), Swift rawRepresentation.
        let mut msg = req.nonce.as_bytes().to_vec();
        msg.extend_from_slice(req.device_id.as_bytes());
        msg.extend_from_slice(&issued_at.to_be_bytes());
        let sig_bytes = B64.decode(&req.signature_b64)?;
        verify_p256_signature(&pk_bytes, &msg, &sig_bytes)
            .map_err(|e| anyhow::anyhow!("Invalid registration signature: {}", e))?;

        // 4. Check device limit — auto-evict the oldest if at capacity
        let mut devices = self.list_devices()?;
        if devices.len() >= MAX_WATCH_DEVICES {
            // Sort oldest first by registered_at and remove it
            devices.sort_by_key(|d| d.registered_at);
            if let Some(oldest) = devices.first() {
                let old_id = oldest.device_id.clone();
                tracing::info!("Watch device limit reached; evicting oldest device {}", old_id);
                let store = crate::profile_store::ProfileStore::new()
                    .map_err(|e| anyhow::anyhow!("{}", e))?;
                let key = format!("watch.device.{}.record", old_id);
                let _ = store.delete_api_key("default", &key);
            }
        }

        // 5. Persist
        let device = WatchDevice {
            device_id: req.device_id.clone(),
            name: req.name.clone(),
            public_key_b64: req.public_key_b64.clone(),
            os_version: req.os_version.clone(),
            model: req.model.clone(),
            registered_at: now,
            last_seen: now,
            revoked_at: None,
            wrist_suspended: false,
        };
        self.save_device(&device)?;
        Ok(device)
    }

    // ── Token issuance ────────────────────────────────────────────────────

    pub fn issue_access_token(&self, device_id: &str) -> Result<(String, u64)> {
        let now = now_unix();
        let exp = now + ACCESS_TOKEN_TTL_SECS;
        let jti: String = format!("{:016x}", rand::thread_rng().gen::<u64>());
        let claims = WatchClaims {
            sub: device_id.to_string(),
            iat: now,
            exp,
            jti,
            machine_id: self.machine_id.clone(),
            kind: "access".into(),
        };
        Ok((self.sign_jwt(&claims)?, exp))
    }

    pub fn issue_refresh_token(&self, device_id: &str) -> Result<String> {
        let now = now_unix();
        let exp = now + REFRESH_TOKEN_TTL_SECS;
        let jti: String = format!("{:016x}", rand::thread_rng().gen::<u64>());
        let claims = WatchClaims {
            sub: device_id.to_string(),
            iat: now,
            exp,
            jti,
            machine_id: self.machine_id.clone(),
            kind: "refresh".into(),
        };
        self.sign_jwt(&claims)
    }

    // ── Token verification ────────────────────────────────────────────────

    /// Verify an access token. Returns device_id on success.
    pub fn verify_access_token(&self, token: &str) -> Result<String> {
        let claims = self.decode_jwt(token)?;
        if claims.kind != "access" {
            bail!("Expected access token, got {}", claims.kind);
        }
        if claims.machine_id != self.machine_id {
            bail!("Token bound to different machine");
        }
        // Check device not revoked / wrist-suspended
        let device = self.load_device(&claims.sub)?;
        if let Some(rev_at) = device.revoked_at {
            if claims.iat < rev_at {
                bail!("Token predates device revocation");
            }
        }
        if device.wrist_suspended {
            bail!("Session suspended — watch removed from wrist");
        }
        Ok(claims.sub)
    }

    // ── Token refresh ─────────────────────────────────────────────────────

    pub fn refresh_tokens(&mut self, req: &WatchRefreshRequest) -> Result<(String, String, u64)> {
        let now = now_unix();
        // Validate timestamp freshness (replay window: 30s)
        if now.saturating_sub(req.timestamp) > 30 || req.timestamp > now + 5 {
            bail!("Refresh request timestamp out of window");
        }
        // Decode and verify refresh token
        let claims = self.decode_jwt(&req.refresh_token)?;
        if claims.kind != "refresh" || claims.sub != req.device_id {
            bail!("Invalid refresh token");
        }
        // Load device and verify P256 proof
        let device = self.load_device(&req.device_id)?;
        let pk_bytes = B64.decode(&device.public_key_b64)?;
        let mut msg = req.refresh_token.as_bytes().to_vec();
        msg.extend_from_slice(&req.timestamp.to_be_bytes());
        let sig_bytes = B64.decode(&req.proof_signature_b64)?;
        verify_p256_signature(&pk_bytes, &msg, &sig_bytes)
            .map_err(|e| anyhow::anyhow!("Invalid proof signature on refresh: {}", e))?;
        // Issue new tokens
        let (access, exp) = self.issue_access_token(&req.device_id)?;
        let refresh = self.issue_refresh_token(&req.device_id)?;
        // Update last_seen
        let mut updated = device;
        updated.last_seen = now;
        self.save_device(&updated)?;
        Ok((access, refresh, exp))
    }

    // ── Wrist event ───────────────────────────────────────────────────────

    /// Handle wrist-on/off event. Suspends session when off wrist.
    pub fn handle_wrist_event(&mut self, ev: &WristEvent) -> Result<()> {
        let now = now_unix();
        if now.saturating_sub(ev.timestamp) > 30 {
            bail!("Wrist event timestamp too stale");
        }
        let mut device = self.load_device(&ev.device_id)?;
        let pk_bytes = B64.decode(&device.public_key_b64)?;
        // Verify: SHA-256(device_id || on_wrist_byte || timestamp_be)
        let mut msg = ev.device_id.as_bytes().to_vec();
        msg.push(ev.on_wrist as u8);
        msg.extend_from_slice(&ev.timestamp.to_be_bytes());
        let sig_bytes = B64.decode(&ev.signature_b64)?;
        verify_p256_signature(&pk_bytes, &msg, &sig_bytes)
            .map_err(|e| anyhow::anyhow!("Invalid wrist-event signature: {}", e))?;
        device.wrist_suspended = !ev.on_wrist;
        self.save_device(&device)?;
        Ok(())
    }

    // ── Device management ─────────────────────────────────────────────────

    pub fn list_devices(&self) -> Result<Vec<WatchDevice>> {
        let store = crate::profile_store::ProfileStore::new()
            .map_err(|e| anyhow::anyhow!("{}", e))?;
        let prefix = "watch.device.";
        // We store device JSON under "watch.device.{id}.record"
        // Enumerate by loading the index key
        let index_raw = store
            .get_api_key("default", "watch.device_index")
            .ok()
            .flatten()
            .unwrap_or_default();
        let ids: Vec<String> = if index_raw.is_empty() {
            vec![]
        } else {
            serde_json::from_str(&index_raw).unwrap_or_default()
        };
        let mut out = Vec::new();
        for id in ids {
            let key = format!("{}{}.record", prefix, id);
            if let Ok(Some(raw)) = store.get_api_key("default", &key) {
                if let Ok(dev) = serde_json::from_str::<WatchDevice>(&raw) {
                    out.push(dev);
                }
            }
        }
        Ok(out)
    }

    pub fn load_device(&self, device_id: &str) -> Result<WatchDevice> {
        let store = crate::profile_store::ProfileStore::new()
            .map_err(|e| anyhow::anyhow!("{}", e))?;
        let key = format!("watch.device.{}.record", device_id);
        let raw = store
            .get_api_key("default", &key)
            .map_err(|e| anyhow::anyhow!("{}", e))?
            .ok_or_else(|| anyhow::anyhow!("Watch device {} not registered", device_id))?;
        Ok(serde_json::from_str(&raw)?)
    }

    pub fn save_device(&self, device: &WatchDevice) -> Result<()> {
        let store = crate::profile_store::ProfileStore::new()
            .map_err(|e| anyhow::anyhow!("{}", e))?;
        let key = format!("watch.device.{}.record", device.device_id);
        store.set_api_key("default", &key, &serde_json::to_string(device)?)
            .map_err(|e| anyhow::anyhow!("{}", e))?;
        // Update index
        let mut ids = self
            .list_devices()
            .unwrap_or_default()
            .into_iter()
            .map(|d| d.device_id)
            .collect::<Vec<_>>();
        if !ids.contains(&device.device_id) {
            ids.push(device.device_id.clone());
        }
        store.set_api_key("default", "watch.device_index", &serde_json::to_string(&ids)?)
            .map_err(|e| anyhow::anyhow!("{}", e))?;
        Ok(())
    }

    pub fn revoke_device(&mut self, device_id: &str) -> Result<()> {
        let mut device = self.load_device(device_id)?;
        device.revoked_at = Some(now_unix());
        self.save_device(&device)
    }

    // ── JWT internals ─────────────────────────────────────────────────────

    fn sign_jwt(&self, claims: &WatchClaims) -> Result<String> {
        let header = B64.encode(b"{\"alg\":\"HS256\",\"typ\":\"JWT\"}");
        let payload = B64.encode(serde_json::to_string(claims)?.as_bytes());
        let signing_input = format!("{}.{}", header, payload);
        let mut mac = HmacSha256::new_from_slice(&self.jwt_secret)
            .map_err(|e| anyhow::anyhow!("{}", e))?;
        mac.update(signing_input.as_bytes());
        let sig = B64.encode(mac.finalize().into_bytes());
        Ok(format!("{}.{}", signing_input, sig))
    }

    fn decode_jwt(&self, token: &str) -> Result<WatchClaims> {
        let parts: Vec<&str> = token.splitn(3, '.').collect();
        if parts.len() != 3 {
            bail!("Malformed JWT");
        }
        let signing_input = format!("{}.{}", parts[0], parts[1]);
        let mut mac = HmacSha256::new_from_slice(&self.jwt_secret)
            .map_err(|e| anyhow::anyhow!("{}", e))?;
        mac.update(signing_input.as_bytes());
        let expected = B64.encode(mac.finalize().into_bytes());
        if !constant_time_eq(parts[2].as_bytes(), expected.as_bytes()) {
            bail!("Invalid JWT signature");
        }
        let payload_json = B64.decode(parts[1])?;
        let claims: WatchClaims = serde_json::from_slice(&payload_json)?;
        let now = now_unix();
        if now > claims.exp {
            bail!("Token expired {} seconds ago", now - claims.exp);
        }
        Ok(claims)
    }

    // ── Test helpers (public, doc-hidden) ────────────────────────────────────

    /// Construct a `WatchAuthManager` directly for testing, bypassing ProfileStore.
    #[doc(hidden)]
    pub fn for_testing(machine_id: impl Into<String>, jwt_secret: Vec<u8>) -> Self {
        Self { machine_id: machine_id.into(), jwt_secret, pending_nonces: Default::default() }
    }

    /// Decode a JWT for testing — exposes the private `decode_jwt` method.
    #[doc(hidden)]
    pub fn decode_jwt_pub(&self, token: &str) -> Result<WatchClaims> {
        self.decode_jwt(token)
    }

    /// Sign a JWT for testing — exposes the private `sign_jwt` method.
    #[doc(hidden)]
    pub fn sign_jwt_pub(&self, claims: &WatchClaims) -> Result<String> {
        self.sign_jwt(claims)
    }

    /// Check whether a nonce is still pending (for single-use tests).
    #[doc(hidden)]
    pub fn has_pending_nonce(&self, nonce: &str) -> bool {
        self.pending_nonces.contains_key(nonce)
    }
}

// ── Crypto helpers ────────────────────────────────────────────────────────────

fn sha256(data: &[u8]) -> Vec<u8> {
    use sha2::Digest;
    sha2::Sha256::digest(data).to_vec()
}

/// Verify P256 ECDSA signature (Apple Secure Enclave key format).
///
/// - `pk`  — 64-byte uncompressed public key (Swift `rawRepresentation`: x||y, no 0x04 prefix)
/// - `msg` — raw message bytes (NOT pre-hashed; SHA-256 is applied internally by p256)
/// - `sig` — 64-byte compact IEEE P1363 signature (r||s, Swift `rawRepresentation`)
pub fn verify_p256_signature(pk: &[u8], msg: &[u8], sig: &[u8]) -> Result<()> {
    use p256::ecdsa::{signature::Verifier, Signature, VerifyingKey};

    // Swift rawRepresentation is the 64-byte x||y form (no 0x04 prefix).
    // p256 expects the full uncompressed form with the 0x04 prefix → prepend it.
    if pk.len() != 64 {
        bail!("P256 public key must be 64 bytes (got {})", pk.len());
    }
    let mut uncompressed = Vec::with_capacity(65);
    uncompressed.push(0x04);
    uncompressed.extend_from_slice(pk);

    let verifying_key = VerifyingKey::from_sec1_bytes(&uncompressed)
        .map_err(|e| anyhow::anyhow!("Invalid P256 public key: {}", e))?;

    // Swift rawRepresentation is already the 64-byte IEEE P1363 (r||s) format.
    if sig.len() != 64 {
        bail!("P256 signature must be 64 bytes (got {})", sig.len());
    }
    let signature = Signature::from_slice(sig)
        .map_err(|e| anyhow::anyhow!("Invalid P256 signature encoding: {}", e))?;

    verifying_key
        .verify(msg, &signature)
        .map_err(|e| anyhow::anyhow!("P256 signature verification failed: {}", e))
}

/// Public wrapper kept for existing BDD step compatibility.
#[doc(hidden)]
pub fn verify_ed25519_signature_pub(pk: &[u8], msg: &[u8], sig: &[u8]) -> Result<()> {
    verify_p256_signature(pk, msg, sig)
}

fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    a.iter().zip(b.iter()).fold(0u8, |acc, (x, y)| acc | (x ^ y)) == 0
}

fn now_unix() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn make_manager() -> (WatchAuthManager, TempDir) {
        let tmp = TempDir::new().unwrap();
        // Override home so ProfileStore goes to tmpdir
        std::env::set_var("VIBE_TEST_PROFILE_DIR", tmp.path());
        // Use a fixed machine_id for determinism
        let mgr = WatchAuthManager {
            machine_id: "test-machine-001".into(),
            jwt_secret: b"test-secret-32-bytes-for-hmac!!!".to_vec(),
            pending_nonces: Default::default(),
        };
        (mgr, tmp)
    }

    #[test]
    fn issue_challenge_returns_nonce() {
        let (mut mgr, _tmp) = make_manager();
        let ch = mgr.issue_challenge().unwrap();
        assert_eq!(ch.nonce.len(), 32);
        assert_eq!(ch.machine_id, "test-machine-001");
        assert!(ch.expires_at > ch.issued_at);
    }

    #[test]
    fn challenge_is_single_use() {
        let (mut mgr, _tmp) = make_manager();
        let ch = mgr.issue_challenge().unwrap();
        // Remove the nonce manually to simulate consumption
        mgr.pending_nonces.remove(&ch.nonce);
        // Second removal should find nothing
        assert!(mgr.pending_nonces.get(&ch.nonce).is_none());
    }

    #[test]
    fn issue_and_verify_access_token() {
        let (mgr, _tmp) = make_manager();
        // Bypass profile store — inject device directly
        let device_id = "watch-abc123";
        let (token, exp) = mgr.issue_access_token(device_id).unwrap();
        assert!(!token.is_empty());
        assert!(exp > now_unix());
        // Decode and check claims (skip full verify since no ProfileStore device)
        let claims = mgr.decode_jwt(&token).unwrap();
        assert_eq!(claims.sub, device_id);
        assert_eq!(claims.kind, "access");
        assert_eq!(claims.machine_id, "test-machine-001");
    }

    #[test]
    fn token_expiry_is_respected() {
        let (mgr, _tmp) = make_manager();
        // Build an already-expired token manually
        let claims = WatchClaims {
            sub: "dev".into(),
            iat: now_unix() - 1000,
            exp: now_unix() - 1,  // expired
            jti: "x".into(),
            machine_id: "test-machine-001".into(),
            kind: "access".into(),
        };
        let token = mgr.sign_jwt(&claims).unwrap();
        let err = mgr.decode_jwt(&token).unwrap_err();
        assert!(err.to_string().contains("expired"));
    }

    #[test]
    fn tampered_token_rejected() {
        let (mgr, _tmp) = make_manager();
        let (mut token, _) = mgr.issue_access_token("dev").unwrap();
        // Flip a byte in the signature part
        let sig_start = token.rfind('.').unwrap() + 1;
        unsafe {
            let bytes = token.as_bytes_mut();
            bytes[sig_start] ^= 0x01;
        }
        assert!(mgr.decode_jwt(&token).is_err());
    }

    #[test]
    fn refresh_token_has_correct_kind() {
        let (mgr, _tmp) = make_manager();
        let token = mgr.issue_refresh_token("dev").unwrap();
        let claims = mgr.decode_jwt(&token).unwrap();
        assert_eq!(claims.kind, "refresh");
    }

    #[test]
    fn sha256_is_deterministic() {
        let a = sha256(b"hello");
        let b = sha256(b"hello");
        assert_eq!(a, b);
        assert_ne!(sha256(b"hello"), sha256(b"world"));
    }

    #[test]
    fn constant_time_eq_correct() {
        assert!(constant_time_eq(b"abc", b"abc"));
        assert!(!constant_time_eq(b"abc", b"abd"));
        assert!(!constant_time_eq(b"abc", b"ab"));
    }

    #[test]
    fn watch_device_serde_roundtrip() {
        let dev = WatchDevice {
            device_id: "abc".into(),
            name: "My Watch".into(),
            public_key_b64: "AAAA".into(),
            os_version: "11.0".into(),
            model: "Watch7,1".into(),
            registered_at: 1_700_000_000,
            last_seen: 1_700_000_000,
            revoked_at: None,
            wrist_suspended: false,
        };
        let json = serde_json::to_string(&dev).unwrap();
        let back: WatchDevice = serde_json::from_str(&json).unwrap();
        assert_eq!(back.device_id, "abc");
        assert_eq!(back.model, "Watch7,1");
        assert!(!back.wrist_suspended);
    }

    // ── RED → GREEN: additional coverage ─────────────────────────────────────

    #[test]
    fn challenge_nonce_is_32_hex_chars() {
        let (mut mgr, _tmp) = make_manager();
        let ch = mgr.issue_challenge().unwrap();
        assert_eq!(ch.nonce.len(), 32);
        assert!(ch.nonce.chars().all(|c| c.is_ascii_hexdigit()),
            "nonce should be lowercase hex");
    }

    #[test]
    fn access_token_ttl_matches_constant() {
        let (mgr, _tmp) = make_manager();
        let (token, exp) = mgr.issue_access_token("dev-ttl").unwrap();
        let claims = mgr.decode_jwt(&token).unwrap();
        assert_eq!(exp, claims.exp);
        // exp - iat should equal ACCESS_TOKEN_TTL_SECS (allow 1s drift)
        assert!((claims.exp - claims.iat).abs_diff(ACCESS_TOKEN_TTL_SECS) <= 1);
    }

    #[test]
    fn refresh_token_kind_differs_from_access() {
        let (mgr, _tmp) = make_manager();
        let (access, _) = mgr.issue_access_token("dev-kind").unwrap();
        let refresh = mgr.issue_refresh_token("dev-kind").unwrap();
        let ac = mgr.decode_jwt(&access).unwrap();
        let rc = mgr.decode_jwt(&refresh).unwrap();
        assert_eq!(ac.kind, "access");
        assert_eq!(rc.kind, "refresh");
        assert_ne!(ac.kind, rc.kind);
    }

    #[test]
    fn token_machine_id_is_embedded() {
        let (mgr, _tmp) = make_manager();
        let (token, _) = mgr.issue_access_token("dev-machine").unwrap();
        let claims = mgr.decode_jwt(&token).unwrap();
        assert_eq!(claims.machine_id, "test-machine-001");
    }

    #[test]
    fn token_from_different_secret_is_rejected() {
        let (mgr_a, _tmp_a) = make_manager();
        let (token, _) = mgr_a.issue_access_token("dev-x").unwrap();
        // Manager with different secret
        let mgr_b = WatchAuthManager {
            machine_id: "test-machine-001".into(),
            jwt_secret: b"different-secret-32-bytes-hmac!!".to_vec(),
            pending_nonces: Default::default(),
        };
        let err = mgr_b.decode_jwt(&token).unwrap_err();
        assert!(err.to_string().contains("signature") || err.to_string().contains("Invalid"));
    }

    #[test]
    fn challenge_window_is_nonce_ttl() {
        let (mut mgr, _tmp) = make_manager();
        let ch = mgr.issue_challenge().unwrap();
        assert_eq!(ch.expires_at - ch.issued_at, NONCE_TTL_SECS);
    }

    #[test]
    fn watch_register_request_serde_roundtrip() {
        let req = WatchRegisterRequest {
            device_id: "did-001".into(),
            name: "Test Watch".into(),
            os_version: "11.0".into(),
            model: "Watch7,1".into(),
            public_key_b64: "AAABBBCCC".into(),
            signature_b64: "SIGSIGSIG".into(),
            nonce: "abc123".into(),
            device_check_token: None,
        };
        let json = serde_json::to_string(&req).unwrap();
        let back: WatchRegisterRequest = serde_json::from_str(&json).unwrap();
        assert_eq!(back.device_id, "did-001");
        assert_eq!(back.model, "Watch7,1");
        assert!(back.device_check_token.is_none());
    }

    #[test]
    fn watch_device_wrist_suspended_serializes() {
        let dev = WatchDevice {
            device_id: "wd".into(),
            name: "W".into(),
            public_key_b64: "A".into(),
            os_version: "11".into(),
            model: "M".into(),
            registered_at: 0,
            last_seen: 0,
            revoked_at: None,
            wrist_suspended: true,
        };
        let json = serde_json::to_string(&dev).unwrap();
        assert!(json.contains("\"wrist_suspended\":true"));
        let back: WatchDevice = serde_json::from_str(&json).unwrap();
        assert!(back.wrist_suspended);
    }

    #[test]
    fn watch_device_revoked_at_serializes() {
        let dev = WatchDevice {
            device_id: "r".into(), name: "R".into(),
            public_key_b64: "K".into(), os_version: "11".into(), model: "M".into(),
            registered_at: 1_700_000_000, last_seen: 1_700_000_001,
            revoked_at: Some(1_700_000_002),
            wrist_suspended: false,
        };
        let json = serde_json::to_string(&dev).unwrap();
        let back: WatchDevice = serde_json::from_str(&json).unwrap();
        assert_eq!(back.revoked_at, Some(1_700_000_002));
    }

    #[test]
    fn verify_ed25519_rejects_short_signature() {
        let pk = vec![0u8; 32];
        let msg = b"test";
        let short_sig = vec![0u8; 63]; // one byte short
        let result = verify_ed25519_signature_pub(&pk, msg, &short_sig);
        assert!(result.is_err());
    }

    #[test]
    fn verify_ed25519_rejects_short_key() {
        let pk = vec![0u8; 31]; // one byte short
        let msg = b"test";
        let sig = vec![0u8; 64];
        let result = verify_ed25519_signature_pub(&pk, msg, &sig);
        assert!(result.is_err());
    }

    #[test]
    fn constant_time_eq_different_lengths_returns_false() {
        assert!(!constant_time_eq(b"abc", b"abcd"));
        assert!(!constant_time_eq(b"", b"a"));
        assert!(constant_time_eq(b"", b""));
    }

    #[test]
    fn wrist_event_stale_timestamp_rejected() {
        let (mut mgr, _tmp) = make_manager();
        // Timestamp 60s in the past — exceeds 30s window
        let stale_ts = now_unix() - 60;
        let ev = WristEvent {
            device_id: "dev-001".into(),
            on_wrist: false,
            timestamp: stale_ts,
            signature_b64: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA".into(),
        };
        let err = mgr.handle_wrist_event(&ev).unwrap_err();
        assert!(err.to_string().contains("stale"));
    }

    #[test]
    fn max_devices_constant_is_ten() {
        assert_eq!(MAX_WATCH_DEVICES, 10);
    }

    // ── RED → GREEN: P256 verification (replaces Ed25519 stub) ───────────────
    // These tests use the p256 crate to generate real keys + signatures so
    // we can verify the server-side verifier is correct end-to-end.

    #[test]
    fn verify_p256_rejects_wrong_key_length() {
        // Ed25519-sized key (32 bytes) must be rejected
        let pk = vec![0u8; 32];
        let msg = b"hello watch";
        let sig = vec![0u8; 64];
        let result = verify_p256_signature(&pk, msg, &sig);
        assert!(result.is_err(), "32-byte key should be rejected (not P256)");
        assert!(result.unwrap_err().to_string().contains("64 bytes"));
    }

    #[test]
    fn verify_p256_rejects_wrong_sig_length() {
        let pk = vec![0u8; 64]; // valid length, random bytes
        let msg = b"hello watch";
        let short_sig = vec![0u8; 63];
        let result = verify_p256_signature(&pk, msg, &short_sig);
        assert!(result.is_err(), "63-byte sig should be rejected");
    }

    #[test]
    fn verify_p256_rejects_invalid_public_key_bytes() {
        // All-zeros is not a valid P256 curve point
        let pk = vec![0u8; 64];
        let msg = b"hello watch";
        let sig = vec![0u8; 64];
        let result = verify_p256_signature(&pk, msg, &sig);
        assert!(result.is_err(), "invalid curve point should be rejected");
    }

    #[test]
    fn verify_p256_valid_signature_accepted() {
        use p256::ecdsa::{signature::Signer, SigningKey};
        use p256::ecdsa::signature::digest::Digest;

        // Generate a real P256 keypair
        let signing_key = SigningKey::random(&mut rand::thread_rng());
        let verifying_key = signing_key.verifying_key();

        // Swift uses: SHA256.hash(data: msg) → sign the hash directly.
        // On the server, verify_p256_signature calls verifying_key.verify(msg)
        // which applies SHA-256 internally — same result.
        let msg = b"nonce_abc device_001 timestamp";

        // Sign via SigningKey::sign (applies SHA-256 internally — same as
        // Secure Enclave's sign(for: SHA256.hash(data:)))
        let sig: p256::ecdsa::Signature = signing_key.sign(msg);

        // Extract raw 64-byte x||y public key (Swift rawRepresentation format)
        let pk_uncompressed = verifying_key.to_encoded_point(false);
        let pk_bytes = &pk_uncompressed.as_bytes()[1..]; // strip 0x04 prefix

        let result = verify_p256_signature(pk_bytes, msg, &sig.to_bytes());
        assert!(result.is_ok(), "valid P256 signature must verify: {:?}", result.err());
    }

    #[test]
    fn verify_p256_wrong_message_rejected() {
        use p256::ecdsa::{signature::Signer, SigningKey};

        let signing_key = SigningKey::random(&mut rand::thread_rng());
        let verifying_key = signing_key.verifying_key();

        let msg = b"correct message";
        let sig: p256::ecdsa::Signature = signing_key.sign(msg);

        let pk_uncompressed = verifying_key.to_encoded_point(false);
        let pk_bytes = &pk_uncompressed.as_bytes()[1..];

        let result = verify_p256_signature(pk_bytes, b"tampered message", &sig.to_bytes());
        assert!(result.is_err(), "signature over different message must be rejected");
    }

    #[test]
    fn verify_p256_wrong_key_rejected() {
        use p256::ecdsa::{signature::Signer, SigningKey};

        let signing_key = SigningKey::random(&mut rand::thread_rng());
        let wrong_key = SigningKey::random(&mut rand::thread_rng());
        let wrong_verifying = wrong_key.verifying_key();

        let msg = b"some message";
        let sig: p256::ecdsa::Signature = signing_key.sign(msg);

        let wrong_pk = wrong_verifying.to_encoded_point(false);
        let wrong_pk_bytes = &wrong_pk.as_bytes()[1..];

        let result = verify_p256_signature(wrong_pk_bytes, msg, &sig.to_bytes());
        assert!(result.is_err(), "signature verified with wrong key must fail");
    }

    #[test]
    fn register_device_full_p256_roundtrip() {
        use p256::ecdsa::{signature::Signer, SigningKey};
        use base64::{engine::general_purpose::URL_SAFE_NO_PAD as B64, Engine};

        let (mut mgr, _tmp) = make_manager();
        let ch = mgr.issue_challenge().unwrap();

        // Simulate what Swift does: generate key, build message, sign
        let signing_key = SigningKey::random(&mut rand::thread_rng());
        let verifying_key = signing_key.verifying_key();
        let device_id = "deadbeef12345678deadbeef12345678";

        let mut msg_bytes = ch.nonce.as_bytes().to_vec();
        msg_bytes.extend_from_slice(device_id.as_bytes());
        msg_bytes.extend_from_slice(&ch.issued_at.to_be_bytes());

        let sig: p256::ecdsa::Signature = signing_key.sign(&msg_bytes);
        let pk_uncompressed = verifying_key.to_encoded_point(false);
        let pk_bytes = &pk_uncompressed.as_bytes()[1..]; // 64-byte x||y

        let req = WatchRegisterRequest {
            device_id: device_id.into(),
            name: "Test Watch".into(),
            os_version: "11.0".into(),
            model: "Watch7,1".into(),
            public_key_b64: B64.encode(pk_bytes),
            signature_b64: B64.encode(sig.to_bytes()),
            nonce: ch.nonce.clone(),
            device_check_token: None,
        };

        let result = mgr.register_device(&req);
        assert!(result.is_ok(), "full P256 registration roundtrip failed: {:?}", result.err());
        let device = result.unwrap();
        assert_eq!(device.device_id, device_id);
    }

    // Legacy Ed25519 pub wrapper tests — now routes through verify_p256_signature
    #[test]
    fn verify_ed25519_pub_rejects_short_key() {
        let pk = vec![0u8; 31]; // too short for P256 (must be 64)
        let result = verify_ed25519_signature_pub(&pk, b"msg", &vec![0u8; 64]);
        assert!(result.is_err());
    }

    #[test]
    fn verify_ed25519_pub_rejects_short_sig() {
        let pk = vec![0u8; 64];
        let result = verify_ed25519_signature_pub(&pk, b"msg", &vec![0u8; 63]);
        assert!(result.is_err());
    }

    #[test]
    fn watch_claims_serde_roundtrip() {
        let claims = WatchClaims {
            sub: "dev-99".into(),
            iat: 1_700_000_000,
            exp: 1_700_000_900,
            jti: "abc123".into(),
            machine_id: "m1".into(),
            kind: "access".into(),
        };
        let json = serde_json::to_string(&claims).unwrap();
        let back: WatchClaims = serde_json::from_str(&json).unwrap();
        assert_eq!(back.sub, "dev-99");
        assert_eq!(back.kind, "access");
    }
}
