/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * How to render any movable tab, from any panel.
 *
 * Settings lets a tab be hosted by a panel other than the one it ships in. The
 * hosting panel has never imported it, so it needs a way to load it by key —
 * that is this file.
 *
 * Only tabs declared through `createComposite` are here. The two hand-built
 * composites (Chat, Diagnostics) build their content inline and pass bespoke
 * props — a chat tab needs its provider list, its pending-write callback and
 * its goal handler — and no generic host can supply those. Settings reads
 * absence from this map as "not movable" and says so on the row.
 *
 * Loading is by `import()` thunk, so importing this module costs the map and
 * nothing else: each panel still arrives in its own chunk when first rendered.
 *
 * GENERATED — do not edit. Run `npm run gen:panel-catalog`.
 */

import type { ComponentType } from "react";

export interface RegisteredTab {
  /** The panel this tab ships in — its identity, which a move does not change. */
  panelId: string;
  tabId: string;
  label: string;
  load: () => Promise<{ default: ComponentType<any> } | Record<string, ComponentType<any>>>;
  /** Named export to pick out of the module, when it has no default. */
  exportName?: string;
}

/** `panelId/tabId` -> how to render it. 226 of 234 tabs. */
export const TAB_REGISTRY: Record<string, RegisteredTab> = {
  "agent-os/dashboard": { panelId: "agent-os", tabId: "dashboard", label: "Dashboard", load: () => import("../components/AgentOSDashboard"), exportName: "AgentOSDashboard" },
  "agent-os/agent": { panelId: "agent-os", tabId: "agent", label: "Agent", load: () => import("../components/AgentPanel"), exportName: "AgentPanel" },
  "agent-os/modes": { panelId: "agent-os", tabId: "modes", label: "Modes", load: () => import("../components/AgentModesPanel") },
  "agent-os/host": { panelId: "agent-os", tabId: "host", label: "Host", load: () => import("../components/AgentHostPanel"), exportName: "AgentHostPanel" },
  "agent-os/branch": { panelId: "agent-os", tabId: "branch", label: "Branch", load: () => import("../components/BranchAgentPanel"), exportName: "BranchAgentPanel" },
  "agent-os/browser": { panelId: "agent-os", tabId: "browser", label: "Browser", load: () => import("../components/BrowserAgentPanel"), exportName: "BrowserAgentPanel" },
  "agent-os/orchestration": { panelId: "agent-os", tabId: "orchestration", label: "Orchestration", load: () => import("../components/OrchestrationPanel"), exportName: "OrchestrationPanel" },
  "agent-os/workflows": { panelId: "agent-os", tabId: "workflows", label: "Workflows", load: () => import("../components/WorkflowsPanel"), exportName: "WorkflowsPanel" },
  "agent-os/loops": { panelId: "agent-os", tabId: "loops", label: "Loops", load: () => import("../components/LoopJobsPanel"), exportName: "LoopJobsPanel" },
  "ai-teams/teams": { panelId: "ai-teams", tabId: "teams", label: "Teams", load: () => import("../components/AgentTeamPanel"), exportName: "AgentTeamPanel" },
  "ai-teams/agentteams": { panelId: "ai-teams", tabId: "agentteams", label: "Hierarchy", load: () => import("../components/AgentTeamsPanel") },
  "ai-teams/subagents": { panelId: "ai-teams", tabId: "subagents", label: "Sub-Agents", load: () => import("../components/SubAgentPanel") },
  "ai-teams/cloud": { panelId: "ai-teams", tabId: "cloud", label: "Cloud", load: () => import("../components/CloudAgentPanel"), exportName: "CloudAgentPanel" },
  "ai-teams/cibot": { panelId: "ai-teams", tabId: "cibot", label: "CI Bot", load: () => import("../components/CIReviewPanel"), exportName: "CIReviewPanel" },
  "ai-teams/agentmodes": { panelId: "ai-teams", tabId: "agentmodes", label: "Modes", load: () => import("../components/AgentModesPanel") },
  "ai-teams/spawnagent": { panelId: "ai-teams", tabId: "spawnagent", label: "Spawn", load: () => import("../components/SpawnAgentPanel") },
  "ai-teams/agenthost": { panelId: "ai-teams", tabId: "agenthost", label: "Host", load: () => import("../components/AgentHostPanel"), exportName: "AgentHostPanel" },
  "ai-playground/counsel": { panelId: "ai-playground", tabId: "counsel", label: "Counsel", load: () => import("../components/CounselPanel"), exportName: "CounselPanel" },
  "ai-playground/superbrain": { panelId: "ai-playground", tabId: "superbrain", label: "SuperBrain", load: () => import("../components/SuperBrainPanel"), exportName: "SuperBrainPanel" },
  "ai-playground/compare": { panelId: "ai-playground", tabId: "compare", label: "Compare", load: () => import("../components/MultiModelPanel"), exportName: "MultiModelPanel" },
  "ai-playground/arena": { panelId: "ai-playground", tabId: "arena", label: "Arena", load: () => import("../components/ArenaPanel"), exportName: "ArenaPanel" },
  "ai-context/icontext": { panelId: "ai-context", tabId: "icontext", label: "Infinite Context", load: () => import("../components/InfiniteContextPanel"), exportName: "InfiniteContextPanel" },
  "ai-context/bundles": { panelId: "ai-context", tabId: "bundles", label: "Bundles", load: () => import("../components/ContextBundlePanel"), exportName: "ContextBundlePanel" },
  "ai-context/openmemory": { panelId: "ai-context", tabId: "openmemory", label: "Open Memory", load: () => import("../components/OpenMemoryPanel") },
  "ai-context/memory-projections": { panelId: "ai-context", tabId: "memory-projections", label: "Projections", load: () => import("../components/MemoryProjectionsPanel"), exportName: "MemoryProjectionsPanel" },
  "ai-context/fastcontext": { panelId: "ai-context", tabId: "fastcontext", label: "Fast Context", load: () => import("../components/FastContextPanel") },
  "ai-context/semanticindex": { panelId: "ai-context", tabId: "semanticindex", label: "Semantic", load: () => import("../components/SemanticIndexPanel"), exportName: "SemanticIndexPanel" },
  "ai-context/webgrounding": { panelId: "ai-context", tabId: "webgrounding", label: "Web Search", load: () => import("../components/WebGroundingPanel"), exportName: "WebGroundingPanel" },
  "ai-context/sessionmemory": { panelId: "ai-context", tabId: "sessionmemory", label: "Session Memory", load: () => import("../components/SessionMemoryPanel"), exportName: "SessionMemoryPanel" },
  "ai-context/artifacts": { panelId: "ai-context", tabId: "artifacts", label: "Artifacts", load: () => import("../components/ArtifactsPanel"), exportName: "ArtifactsPanel" },
  "ai-context/long-context": { panelId: "ai-context", tabId: "long-context", label: "Long Context", load: () => import("../components/LongContextPanel"), exportName: "LongContextPanel" },
  "ai-generation/batchbuilder": { panelId: "ai-generation", tabId: "batchbuilder", label: "Batch Builder", load: () => import("../components/BatchBuilderPanel") },
  "ai-generation/imagegen": { panelId: "ai-generation", tabId: "imagegen", label: "Image Gen", load: () => import("../components/ImageGenPanel") },
  "ai-generation/autoresearch": { panelId: "ai-generation", tabId: "autoresearch", label: "Research", load: () => import("../components/AutoResearchPanel"), exportName: "AutoResearchPanel" },
  "ai-generation/transform": { panelId: "ai-generation", tabId: "transform", label: "Transform", load: () => import("../components/TransformPanel"), exportName: "TransformPanel" },
  "project-hub/workmgmt": { panelId: "project-hub", tabId: "workmgmt", label: "Projects", load: () => import("../components/WorkManagementPanel") },
  "project-hub/dashboard": { panelId: "project-hub", tabId: "dashboard", label: "Dashboard", load: () => import("../components/DashboardPanel") },
  "project-hub/steering": { panelId: "project-hub", tabId: "steering", label: "Steering", load: () => import("../components/SteeringPanel") },
  "project-hub/soul": { panelId: "project-hub", tabId: "soul", label: "Soul", load: () => import("../components/SoulPanel"), exportName: "SoulPanel" },
  "project-hub/rules": { panelId: "project-hub", tabId: "rules", label: "Rules", load: () => import("../components/MemoryPanel"), exportName: "MemoryPanel" },
  "planning/specs": { panelId: "planning", tabId: "specs", label: "Specs", load: () => import("../components/SpecPanel"), exportName: "SpecPanel" },
  "planning/plandoc": { panelId: "planning", tabId: "plandoc", label: "Plan Doc", load: () => import("../components/PlanDocumentPanel") },
  "planning/workflow": { panelId: "planning", tabId: "workflow", label: "Workflow", load: () => import("../components/WorkflowPanel"), exportName: "WorkflowPanel" },
  "planning/orchestration": { panelId: "planning", tabId: "orchestration", label: "Tasks", load: () => import("../components/OrchestrationPanel"), exportName: "OrchestrationPanel" },
  "planning/clarify": { panelId: "planning", tabId: "clarify", label: "Clarify", load: () => import("../components/ClarifyingQuestionsPanel") },
  "planning/codesearch": { panelId: "planning", tabId: "codesearch", label: "Search", load: () => import("../components/ConversationalSearchPanel") },
  "planning/nexttask": { panelId: "planning", tabId: "nexttask", label: "Next Task", load: () => import("../components/NextTaskPanel"), exportName: "NextTaskPanel" },
  "planning/docsync": { panelId: "planning", tabId: "docsync", label: "Doc Sync", load: () => import("../components/DocSyncPanel"), exportName: "DocSyncPanel" },
  "observability/traces": { panelId: "observability", tabId: "traces", label: "Traces", load: () => import("../components/TraceDashboard"), exportName: "TraceDashboard" },
  "observability/recording": { panelId: "observability", tabId: "recording", label: "Recording", load: () => import("../components/AgentRecordingPanel"), exportName: "AgentRecordingPanel" },
  "observability/demo": { panelId: "observability", tabId: "demo", label: "Demo", load: () => import("../components/DemoPanel"), exportName: "DemoPanel" },
  "observability/proactive": { panelId: "observability", tabId: "proactive", label: "Proactive", load: () => import("../components/ProactivePanel"), exportName: "ProactivePanel" },
  "design/hub": { panelId: "design", tabId: "hub", label: "Hub", load: () => import("../components/DesignHubPanel"), exportName: "DesignHubPanel" },
  "design/import": { panelId: "design", tabId: "import", label: "Import", load: () => import("../components/DesignImportPanel") },
  "design/design": { panelId: "design", tabId: "design", label: "Design", load: () => import("../components/DesignMode"), exportName: "DesignMode" },
  "design/annotations": { panelId: "design", tabId: "annotations", label: "Annotations", load: () => import("../components/DesignAnnotationsPanel"), exportName: "DesignAnnotationsPanel" },
  "design/sketch": { panelId: "design", tabId: "sketch", label: "Sketch", load: () => import("../components/SketchCanvasPanel"), exportName: "SketchCanvasPanel" },
  "design/img2app": { panelId: "design", tabId: "img2app", label: "Screenshot to App", load: () => import("../components/ScreenshotToApp"), exportName: "ScreenshotToApp" },
  "security/review": { panelId: "security", tabId: "review", label: "Review", load: () => import("../components/SecurityReviewPanel"), exportName: "SecurityReviewPanel" },
  "security/redteam": { panelId: "security", tabId: "redteam", label: "Red Team", load: () => import("../components/RedTeamPanel"), exportName: "RedTeamPanel" },
  "security/blueteam": { panelId: "security", tabId: "blueteam", label: "Blue Team", load: () => import("../components/BlueTeamPanel"), exportName: "BlueTeamPanel" },
  "security/purpleteam": { panelId: "security", tabId: "purpleteam", label: "Purple Team", load: () => import("../components/PurpleTeamPanel"), exportName: "PurpleTeamPanel" },
  "security/securityscan": { panelId: "security", tabId: "securityscan", label: "Scanner", load: () => import("../components/SecurityScanPanel") },
  "testing/tests": { panelId: "testing", tabId: "tests", label: "Tests", load: () => import("../components/TestPanel"), exportName: "TestPanel" },
  "testing/coverage": { panelId: "testing", tabId: "coverage", label: "Coverage", load: () => import("../components/CoveragePanel"), exportName: "CoveragePanel" },
  "testing/bugbot": { panelId: "testing", tabId: "bugbot", label: "BugBot", load: () => import("../components/BugBotPanel"), exportName: "BugBotPanel" },
  "testing/autofix": { panelId: "testing", tabId: "autofix", label: "Autofix", load: () => import("../components/AutofixPanel"), exportName: "AutofixPanel" },
  "testing/cloudautofix": { panelId: "testing", tabId: "cloudautofix", label: "Cloud Fix", load: () => import("../components/CloudAutofixPanel") },
  "testing/qa-validation": { panelId: "testing", tabId: "qa-validation", label: "QA", load: () => import("../components/QaValidationPanel"), exportName: "QaValidationPanel" },
  "testing/visualverify": { panelId: "testing", tabId: "visualverify", label: "Visual Verify", load: () => import("../components/VisualVerifyPanel"), exportName: "VisualVerifyPanel" },
  "testing/mctsrepair": { panelId: "testing", tabId: "mctsrepair", label: "MCTS Repair", load: () => import("../components/MctsRepairPanel"), exportName: "MctsRepairPanel" },
  "testing/swebench": { panelId: "testing", tabId: "swebench", label: "SWE-Bench", load: () => import("../components/SweBenchPanel"), exportName: "SweBenchPanel" },
  "testing/visualtest": { panelId: "testing", tabId: "visualtest", label: "Visual Test", load: () => import("../components/VisualTestPanel") },
  "code-analysis/metrics": { panelId: "code-analysis", tabId: "metrics", label: "Metrics", load: () => import("../components/CodeMetricsPanel"), exportName: "CodeMetricsPanel" },
  "code-analysis/astedit": { panelId: "code-analysis", tabId: "astedit", label: "AST Edit", load: () => import("../components/AstEditPanel") },
  "code-analysis/editpredict": { panelId: "code-analysis", tabId: "editpredict", label: "Predict", load: () => import("../components/EditPredictionPanel") },
  "code-analysis/snippets": { panelId: "code-analysis", tabId: "snippets", label: "Snippets", load: () => import("../components/SnippetPanel"), exportName: "SnippetPanel" },
  "code-analysis/healthscore": { panelId: "code-analysis", tabId: "healthscore", label: "Health Score", load: () => import("../components/HealthScorePanel") },
  "code-analysis/intentrefactor": { panelId: "code-analysis", tabId: "intentrefactor", label: "Refactor", load: () => import("../components/IntentRefactorPanel") },
  "code-analysis/reviewprotocol": { panelId: "code-analysis", tabId: "reviewprotocol", label: "Review", load: () => import("../components/ReviewProtocolPanel") },
  "code-analysis/aicodereview": { panelId: "code-analysis", tabId: "aicodereview", label: "AI Review", load: () => import("../components/AiCodeReviewPanel") },
  "architecture/archspec": { panelId: "architecture", tabId: "archspec", label: "Architecture", load: () => import("../components/ArchitectureSpecPanel") },
  "architecture/policy": { panelId: "architecture", tabId: "policy", label: "Policy Engine", load: () => import("../components/PolicyEnginePanel") },
  "version-control/history": { panelId: "version-control", tabId: "history", label: "History", load: () => import("../components/HistoryPanel"), exportName: "HistoryPanel" },
  "version-control/checkpoints": { panelId: "version-control", tabId: "checkpoints", label: "Checkpoints", load: () => import("../components/CheckpointPanel"), exportName: "CheckpointPanel" },
  "version-control/bisect": { panelId: "version-control", tabId: "bisect", label: "Bisect", load: () => import("../components/BisectPanel"), exportName: "BisectPanel" },
  "collaboration/collab-chat": { panelId: "collaboration", tabId: "collab-chat", label: "Collab Chat", load: () => import("../components/CollabChatPanel"), exportName: "CollabChatPanel" },
  "collaboration/collab": { panelId: "collaboration", tabId: "collab", label: "Collab", load: () => import("../components/CollabPanel"), exportName: "CollabPanel" },
  "collaboration/remotecontrol": { panelId: "collaboration", tabId: "remotecontrol", label: "Remote", load: () => import("../components/RemoteControlPanel"), exportName: "RemoteControlPanel" },
  "collaboration/gateway-sandbox": { panelId: "collaboration", tabId: "gateway-sandbox", label: "Msg Gateway", load: () => import("../components/GatewaySandboxPanel"), exportName: "GatewaySandboxPanel" },
  "build-deploy/build": { panelId: "build-deploy", tabId: "build", label: "Build", load: () => import("../components/BuildPanel"), exportName: "BuildPanel" },
  "build-deploy/deploy": { panelId: "build-deploy", tabId: "deploy", label: "Deploy", load: () => import("../components/DeployPanel"), exportName: "DeployPanel" },
  "build-deploy/scaffold": { panelId: "build-deploy", tabId: "scaffold", label: "Scaffold", load: () => import("../components/ScaffoldPanel"), exportName: "ScaffoldPanel" },
  "build-deploy/appbuilder": { panelId: "build-deploy", tabId: "appbuilder", label: "App Builder", load: () => import("../components/AppBuilderPanel"), exportName: "AppBuilderPanel" },
  "build-deploy/fullstack": { panelId: "build-deploy", tabId: "fullstack", label: "Full Stack", load: () => import("../components/FullStackGenPanel") },
  "build-deploy/worktreepool": { panelId: "build-deploy", tabId: "worktreepool", label: "Worktrees", load: () => import("../components/WorktreePoolPanel"), exportName: "WorktreePoolPanel" },
  "build-deploy/auto-deploy": { panelId: "build-deploy", tabId: "auto-deploy", label: "Auto Deploy", load: () => import("../components/AutoDeployPanel"), exportName: "AutoDeployPanel" },
  "containers/docker": { panelId: "containers", tabId: "docker", label: "Docker", load: () => import("../components/DockerPanel"), exportName: "DockerPanel" },
  "containers/k8s": { panelId: "containers", tabId: "k8s", label: "K8s", load: () => import("../components/K8sPanel") },
  "containers/sandbox": { panelId: "containers", tabId: "sandbox", label: "Sandbox", load: () => import("../components/SandboxPanel"), exportName: "SandboxPanel" },
  "containers/cloudsandbox": { panelId: "containers", tabId: "cloudsandbox", label: "Cloud Sandbox", load: () => import("../components/CloudSandboxPanel") },
  "ci-cd/pipeline": { panelId: "ci-cd", tabId: "pipeline", label: "Pipeline", load: () => import("../components/CicdPanel") },
  "ci-cd/status": { panelId: "ci-cd", tabId: "status", label: "Status", load: () => import("../components/CiStatusPanel") },
  "ci-cd/gates": { panelId: "ci-cd", tabId: "gates", label: "Gates", load: () => import("../components/CiGatesPanel") },
  "cloud-platform/providers": { panelId: "cloud-platform", tabId: "providers", label: "Providers", load: () => import("../components/CloudProviderPanel"), exportName: "CloudProviderPanel" },
  "cloud-platform/env": { panelId: "cloud-platform", tabId: "env", label: "Environment", load: () => import("../components/EnvPanel"), exportName: "EnvPanel" },
  "cloud-platform/health": { panelId: "cloud-platform", tabId: "health", label: "Health", load: () => import("../components/HealthMonitorPanel"), exportName: "HealthMonitorPanel" },
  "cloud-platform/idp": { panelId: "cloud-platform", tabId: "idp", label: "IDP", load: () => import("../components/IdpPanel"), exportName: "IdpPanel" },
  "ai-ml/workflow": { panelId: "ai-ml", tabId: "workflow", label: "Workflow", load: () => import("../components/AiMlWorkflowPanel"), exportName: "AiMlWorkflowPanel" },
  "ai-ml/wizard": { panelId: "ai-ml", tabId: "wizard", label: "Wizard", load: () => import("../components/ModelWizardPanel"), exportName: "ModelWizardPanel" },
  "ai-ml/training": { panelId: "ai-ml", tabId: "training", label: "Training", load: () => import("../components/TrainingPanel"), exportName: "TrainingPanel" },
  "ai-ml/inference": { panelId: "ai-ml", tabId: "inference", label: "Inference", load: () => import("../components/InferencePanel"), exportName: "InferencePanel" },
  "ai-ml/quantum": { panelId: "ai-ml", tabId: "quantum", label: "Quantum", load: () => import("../components/QuantumComputingPanel"), exportName: "QuantumComputingPanel" },
  "ai-ml/rlcef": { panelId: "ai-ml", tabId: "rlcef", label: "RLCEF", load: () => import("../components/RlcefPanel"), exportName: "RlcefPanel" },
  "ai-ml/skilldistill": { panelId: "ai-ml", tabId: "skilldistill", label: "Distillation", load: () => import("../components/SkillDistillationPanel") },
  "ai-ml/skillforge": { panelId: "ai-ml", tabId: "skillforge", label: "SkillForge", load: () => import("../components/SkillForgePanel"), exportName: "SkillForgePanel" },
  "ai-ml/selfimproving": { panelId: "ai-ml", tabId: "selfimproving", label: "Self-Improving", load: () => import("../components/SelfImprovingSkillsPanel"), exportName: "SelfImprovingSkillsPanel" },
  "ai-ml/on-device": { panelId: "ai-ml", tabId: "on-device", label: "On-Device", load: () => import("../components/OnDevicePanel"), exportName: "OnDevicePanel" },
  "ai-ml/voice-vocab": { panelId: "ai-ml", tabId: "voice-vocab", label: "Voice Vocab", load: () => import("../components/VoiceVocabPanel"), exportName: "VoiceVocabPanel" },
  "rl-os/training": { panelId: "rl-os", tabId: "training", label: "Training", load: () => import("../components/RLTrainingDashboard"), exportName: "RLTrainingDashboard" },
  "rl-os/environments": { panelId: "rl-os", tabId: "environments", label: "Environments", load: () => import("../components/RLEnvironmentViewer"), exportName: "RLEnvironmentViewer" },
  "rl-os/eval": { panelId: "rl-os", tabId: "eval", label: "Evaluation", load: () => import("../components/RLEvalResults"), exportName: "RLEvalResults" },
  "rl-os/optimization": { panelId: "rl-os", tabId: "optimization", label: "Optimization", load: () => import("../components/RLOptimizationReport"), exportName: "RLOptimizationReport" },
  "rl-os/deployment": { panelId: "rl-os", tabId: "deployment", label: "Deployment", load: () => import("../components/RLDeploymentMonitor"), exportName: "RLDeploymentMonitor" },
  "rl-os/comparison": { panelId: "rl-os", tabId: "comparison", label: "Compare", load: () => import("../components/RLPolicyComparison"), exportName: "RLPolicyComparison" },
  "rl-os/lineage": { panelId: "rl-os", tabId: "lineage", label: "Lineage", load: () => import("../components/RLModelLineage"), exportName: "RLModelLineage" },
  "rl-os/multiagent": { panelId: "rl-os", tabId: "multiagent", label: "Multi-Agent", load: () => import("../components/RLMultiAgentView"), exportName: "RLMultiAgentView" },
  "rl-os/rewards": { panelId: "rl-os", tabId: "rewards", label: "Rewards", load: () => import("../components/RLRewardDecomposition"), exportName: "RLRewardDecomposition" },
  "rl-os/rlhf": { panelId: "rl-os", tabId: "rlhf", label: "RLHF", load: () => import("../components/RLHFAlignmentDashboard"), exportName: "RLHFAlignmentDashboard" },
  "database/connections": { panelId: "database", tabId: "connections", label: "Connections", load: () => import("../components/DatabasePanel"), exportName: "DatabasePanel" },
  "database/migrations": { panelId: "database", tabId: "migrations", label: "Migrations", load: () => import("../components/MigrationsPanel"), exportName: "MigrationsPanel" },
  "database/vectordb": { panelId: "database", tabId: "vectordb", label: "Vector DB", load: () => import("../components/VectorDbPanel"), exportName: "VectorDbPanel" },
  "database/turboquant": { panelId: "database", tabId: "turboquant", label: "TurboQuant", load: () => import("../components/TurboQuantPanel"), exportName: "TurboQuantPanel" },
  "api-tools/http": { panelId: "api-tools", tabId: "http", label: "HTTP", load: () => import("../components/HttpPlayground"), exportName: "HttpPlayground" },
  "api-tools/graphql": { panelId: "api-tools", tabId: "graphql", label: "GraphQL", load: () => import("../components/GraphQLPanel"), exportName: "GraphQLPanel" },
  "api-tools/mock": { panelId: "api-tools", tabId: "mock", label: "Mock Server", load: () => import("../components/MockServerPanel"), exportName: "MockServerPanel" },
  "api-tools/websocket": { panelId: "api-tools", tabId: "websocket", label: "WebSocket", load: () => import("../components/WebSocketPanel"), exportName: "WebSocketPanel" },
  "api-tools/docs": { panelId: "api-tools", tabId: "docs", label: "Docs", load: () => import("../components/ApiDocsPanel"), exportName: "ApiDocsPanel" },
  "data-pipeline/streaming": { panelId: "data-pipeline", tabId: "streaming", label: "Streaming", load: () => import("../components/StreamingPanel"), exportName: "StreamingPanel" },
  "data-pipeline/ingest": { panelId: "data-pipeline", tabId: "ingest", label: "Ingest", load: () => import("../components/DocumentIngestPanel"), exportName: "DocumentIngestPanel" },
  "data-pipeline/crawler": { panelId: "data-pipeline", tabId: "crawler", label: "Crawler", load: () => import("../components/WebCrawlerPanel"), exportName: "WebCrawlerPanel" },
  "system-monitor/processes": { panelId: "system-monitor", tabId: "processes", label: "Processes", load: () => import("../components/ProcessPanel") },
  "system-monitor/profiler": { panelId: "system-monitor", tabId: "profiler", label: "Profiler", load: () => import("../components/ProfilerPanel"), exportName: "ProfilerPanel" },
  "system-monitor/debug": { panelId: "system-monitor", tabId: "debug", label: "Debug", load: () => import("../components/DebugModePanel") },
  "system-monitor/observeact": { panelId: "system-monitor", tabId: "observeact", label: "Observe-Act", load: () => import("../components/ObserveActPanel"), exportName: "ObserveActPanel" },
  "system-monitor/desktop": { panelId: "system-monitor", tabId: "desktop", label: "Desktop", load: () => import("../components/DesktopAgentPanel"), exportName: "DesktopAgentPanel" },
  "terminal/scripts": { panelId: "terminal", tabId: "scripts", label: "Scripts", load: () => import("../components/ScriptPanel"), exportName: "ScriptPanel" },
  "terminal/ssh": { panelId: "terminal", tabId: "ssh", label: "SSH", load: () => import("../components/SshPanel"), exportName: "SshPanel" },
  "terminal/notebook": { panelId: "terminal", tabId: "notebook", label: "Notebook", load: () => import("../components/NotebookPanel"), exportName: "NotebookPanel" },
  "terminal/logs": { panelId: "terminal", tabId: "logs", label: "Logs", load: () => import("../components/LogPanel"), exportName: "LogPanel" },
  "terminal/voicelocal": { panelId: "terminal", tabId: "voicelocal", label: "Voice", load: () => import("../components/VoiceLocalPanel"), exportName: "VoiceLocalPanel" },
  "converters/encoding": { panelId: "converters", tabId: "encoding", label: "Encoding", load: () => import("../components/EncodingPanel"), exportName: "EncodingPanel" },
  "converters/numbers": { panelId: "converters", tabId: "numbers", label: "Numbers", load: () => import("../components/NumberBasePanel"), exportName: "NumberBasePanel" },
  "converters/colorconv": { panelId: "converters", tabId: "colorconv", label: "Colors", load: () => import("../components/ColorConverterPanel"), exportName: "ColorConverterPanel" },
  "converters/units": { panelId: "converters", tabId: "units", label: "Units", load: () => import("../components/UnitConverterPanel"), exportName: "UnitConverterPanel" },
  "converters/unicode": { panelId: "converters", tabId: "unicode", label: "Unicode", load: () => import("../components/UnicodePanel"), exportName: "UnicodePanel" },
  "converters/timestamp": { panelId: "converters", tabId: "timestamp", label: "Timestamp", load: () => import("../components/TimestampPanel"), exportName: "TimestampPanel" },
  "formatters/regex": { panelId: "formatters", tabId: "regex", label: "Regex", load: () => import("../components/RegexPanel"), exportName: "RegexPanel" },
  "formatters/jwt": { panelId: "formatters", tabId: "jwt", label: "JWT", load: () => import("../components/JwtPanel"), exportName: "JwtPanel" },
  "formatters/jsontools": { panelId: "formatters", tabId: "jsontools", label: "JSON", load: () => import("../components/JsonToolsPanel"), exportName: "JsonToolsPanel" },
  "formatters/cron": { panelId: "formatters", tabId: "cron", label: "Cron", load: () => import("../components/CronPanel"), exportName: "CronPanel" },
  "formatters/csv": { panelId: "formatters", tabId: "csv", label: "CSV", load: () => import("../components/CsvPanel"), exportName: "CsvPanel" },
  "formatters/cidr": { panelId: "formatters", tabId: "cidr", label: "CIDR", load: () => import("../components/CidrPanel"), exportName: "CidrPanel" },
  "formatters/datagen": { panelId: "formatters", tabId: "datagen", label: "Data Gen", load: () => import("../components/DataGenPanel"), exportName: "DataGenPanel" },
  "formatters/utils": { panelId: "formatters", tabId: "utils", label: "Utils", load: () => import("../components/UtilitiesPanel"), exportName: "UtilitiesPanel" },
  "editors/difftool": { panelId: "editors", tabId: "difftool", label: "Diff", load: () => import("../components/DiffToolPanel"), exportName: "DiffToolPanel" },
  "editors/markdown": { panelId: "editors", tabId: "markdown", label: "Markdown", load: () => import("../components/MarkdownPanel"), exportName: "MarkdownPanel" },
  "editors/canvas": { panelId: "editors", tabId: "canvas", label: "Canvas", load: () => import("../components/CanvasPanel") },
  "editors/colors": { panelId: "editors", tabId: "colors", label: "Palette", load: () => import("../components/ColorPalettePanel"), exportName: "ColorPalettePanel" },
  "config/keys": { panelId: "config", tabId: "keys", label: "Keys", load: () => import("../components/KeysPanel"), exportName: "KeysPanel" },
  "config/models": { panelId: "config", tabId: "models", label: "Models", load: () => import("../components/ModelManagerPanel"), exportName: "ModelManagerPanel" },
  "config/settings": { panelId: "config", tabId: "settings", label: "Settings", load: () => import("../components/SettingsPanel"), exportName: "SettingsPanel" },
  "config/security": { panelId: "config", tabId: "security", label: "Security", load: () => import("../components/SecurityPanel"), exportName: "SecurityPanel" },
  "config/hooks": { panelId: "config", tabId: "hooks", label: "Hooks", load: () => import("../components/HooksPanel"), exportName: "HooksPanel" },
  "config/markers": { panelId: "config", tabId: "markers", label: "Bookmarks", load: () => import("../components/BookmarkPanel"), exportName: "BookmarkPanel" },
  "config/jobs": { panelId: "config", tabId: "jobs", label: "Jobs", load: () => import("../components/BackgroundJobsPanel"), exportName: "BackgroundJobsPanel" },
  "integrations/mcp": { panelId: "integrations", tabId: "mcp", label: "MCP", load: () => import("../components/McpPanel"), exportName: "McpPanel" },
  "integrations/acpprotocol": { panelId: "integrations", tabId: "acpprotocol", label: "ACP", load: () => import("../components/AcpPanel"), exportName: "AcpPanel" },
  "integrations/webhooks": { panelId: "integrations", tabId: "webhooks", label: "Webhooks", load: () => import("../components/WebhookPanel"), exportName: "WebhookPanel" },
  "integrations/connectors": { panelId: "integrations", tabId: "connectors", label: "Connectors", load: () => import("../components/ConnectorsPanel"), exportName: "ConnectorsPanel" },
  "integrations/a2a": { panelId: "integrations", tabId: "a2a", label: "A2A", load: () => import("../components/A2aPanel"), exportName: "A2aPanel" },
  "integrations/langgraph": { panelId: "integrations", tabId: "langgraph", label: "LangGraph", load: () => import("../components/LangGraphPanel"), exportName: "LangGraphPanel" },
  "integrations/ide-bridge": { panelId: "integrations", tabId: "ide-bridge", label: "IDE Bridge", load: () => import("../components/IdeBridgePanel"), exportName: "IdeBridgePanel" },
  "administration/admin": { panelId: "administration", tabId: "admin", label: "Admin", load: () => import("../components/AdminPanel"), exportName: "AdminPanel" },
  "administration/auth": { panelId: "administration", tabId: "auth", label: "Auth", load: () => import("../components/AuthPanel"), exportName: "AuthPanel" },
  "administration/governance": { panelId: "administration", tabId: "governance", label: "Governance", load: () => import("../components/TeamGovernancePanel") },
  "administration/sessions": { panelId: "administration", tabId: "sessions", label: "Sessions", load: () => import("../components/SessionBrowserPanel") },
  "administration/manager": { panelId: "administration", tabId: "manager", label: "Manager", load: () => import("../components/ManagerView"), exportName: "ManagerView" },
  "administration/analytics": { panelId: "administration", tabId: "analytics", label: "Analytics", load: () => import("../components/AnalyticsPanel"), exportName: "AnalyticsPanel" },
  "administration/trust": { panelId: "administration", tabId: "trust", label: "Trust", load: () => import("../components/TrustPanel"), exportName: "TrustPanel" },
  "administration/compliance": { panelId: "administration", tabId: "compliance", label: "Compliance", load: () => import("../components/CompliancePanel"), exportName: "CompliancePanel" },
  "billing/cost": { panelId: "billing", tabId: "cost", label: "Cost", load: () => import("../components/CostPanel"), exportName: "CostPanel" },
  "billing/usagemetering": { panelId: "billing", tabId: "usagemetering", label: "Usage", load: () => import("../components/UsageMeteringPanel"), exportName: "UsageMeteringPanel" },
  "billing/costrouter": { panelId: "billing", tabId: "costrouter", label: "Router", load: () => import("../components/CostRouterPanel"), exportName: "CostRouterPanel" },
  "tools-settings/automations": { panelId: "tools-settings", tabId: "automations", label: "Automations", load: () => import("../components/AutomationsPanel"), exportName: "AutomationsPanel" },
  "tools-settings/selfreview": { panelId: "tools-settings", tabId: "selfreview", label: "Self-Review", load: () => import("../components/SelfReviewPanel"), exportName: "SelfReviewPanel" },
  "tools-settings/artifacts": { panelId: "tools-settings", tabId: "artifacts", label: "Artifacts", load: () => import("../components/ArtifactsPanel"), exportName: "ArtifactsPanel" },
  "productivity/productivity": { panelId: "productivity", tabId: "productivity", label: "Productivity", load: () => import("../components/ProductivityPanel"), exportName: "ProductivityPanel" },
  "company/company-dashboard": { panelId: "company", tabId: "company-dashboard", label: "Dashboard", load: () => import("../components/CompanyDashboardPanel"), exportName: "CompanyDashboardPanel" },
  "company/company-org": { panelId: "company", tabId: "company-org", label: "Org Chart", load: () => import("../components/CompanyOrgChartPanel"), exportName: "CompanyOrgChartPanel" },
  "company/company-agents": { panelId: "company", tabId: "company-agents", label: "Agents", load: () => import("../components/CompanyAgentDetailPanel"), exportName: "CompanyAgentDetailPanel" },
  "company/company-goals": { panelId: "company", tabId: "company-goals", label: "Agent Goals", load: () => import("../components/CompanyGoalsPanel"), exportName: "CompanyGoalsPanel" },
  "company/company-tasks": { panelId: "company", tabId: "company-tasks", label: "Agent Tasks", load: () => import("../components/CompanyTaskBoardPanel"), exportName: "CompanyTaskBoardPanel" },
  "company/company-approvals": { panelId: "company", tabId: "company-approvals", label: "Approvals", load: () => import("../components/CompanyApprovalsPanel"), exportName: "CompanyApprovalsPanel" },
  "company/company-budget": { panelId: "company", tabId: "company-budget", label: "Budget", load: () => import("../components/CompanyBudgetPanel"), exportName: "CompanyBudgetPanel" },
  "company/company-secrets": { panelId: "company", tabId: "company-secrets", label: "Secrets", load: () => import("../components/CompanySecretsPanel"), exportName: "CompanySecretsPanel" },
  "company/company-routines": { panelId: "company", tabId: "company-routines", label: "Routines", load: () => import("../components/CompanyRoutinesPanel"), exportName: "CompanyRoutinesPanel" },
  "company/company-heartbeats": { panelId: "company", tabId: "company-heartbeats", label: "Heartbeats", load: () => import("../components/CompanyHeartbeatPanel"), exportName: "CompanyHeartbeatPanel" },
  "company/company-docs": { panelId: "company", tabId: "company-docs", label: "Agent Docs", load: () => import("../components/CompanyDocumentsPanel"), exportName: "CompanyDocumentsPanel" },
  "company/company-portability": { panelId: "company", tabId: "company-portability", label: "Import/Export", load: () => import("../components/CompanyPortabilityPanel"), exportName: "CompanyPortabilityPanel" },
  "company/company-adapters": { panelId: "company", tabId: "company-adapters", label: "Adapters", load: () => import("../components/CompanyAdapterPanel"), exportName: "CompanyAdapterPanel" },
  "company/workspace-config": { panelId: "company", tabId: "workspace-config", label: "Workspace Config", load: () => import("../components/CompanyWorkspaceConfigPanel"), exportName: "CompanyWorkspaceConfigPanel" },
  "company/priority-map": { panelId: "company", tabId: "priority-map", label: "Priority Map", load: () => import("../components/CompanyPriorityMapPanel"), exportName: "CompanyPriorityMapPanel" },
  "agent-intelligence/env-dispatch": { panelId: "agent-intelligence", tabId: "env-dispatch", label: "Env Dispatch", load: () => import("../components/EnvDispatchPanel"), exportName: "EnvDispatchPanel" },
  "agent-intelligence/nested-agents": { panelId: "agent-intelligence", tabId: "nested-agents", label: "Nested Agents", load: () => import("../components/NestedAgentsPanel"), exportName: "NestedAgentsPanel" },
  "agent-intelligence/thought-stream": { panelId: "agent-intelligence", tabId: "thought-stream", label: "Thought Stream", load: () => import("../components/ThoughtStreamPanel"), exportName: "ThoughtStreamPanel" },
  "agent-intelligence/hard-problem": { panelId: "agent-intelligence", tabId: "hard-problem", label: "Hard Problem", load: () => import("../components/HardProblemPanel"), exportName: "HardProblemPanel" },
  "agent-intelligence/repro-agent": { panelId: "agent-intelligence", tabId: "repro-agent", label: "Repro Agent", load: () => import("../components/ReproAgentPanel"), exportName: "ReproAgentPanel" },
  "enterprise-governance/mcp-governance": { panelId: "enterprise-governance", tabId: "mcp-governance", label: "MCP Governance", load: () => import("../components/McpGovernancePanel"), exportName: "McpGovernancePanel" },
  "enterprise-governance/security-posture": { panelId: "enterprise-governance", tabId: "security-posture", label: "Security Posture", load: () => import("../components/SecurityPosturePanel"), exportName: "SecurityPosturePanel" },
  "enterprise-governance/plugin-governance": { panelId: "enterprise-governance", tabId: "plugin-governance", label: "Plugin Governance", load: () => import("../components/PluginGovernancePanel"), exportName: "PluginGovernancePanel" },
  "enterprise-governance/msaf": { panelId: "enterprise-governance", tabId: "msaf", label: "MSAF", load: () => import("../components/MsafPanel"), exportName: "MsafPanel" },
  "enterprise-governance/team-onboarding": { panelId: "enterprise-governance", tabId: "team-onboarding", label: "Team Onboarding", load: () => import("../components/TeamOnboardingPanel"), exportName: "TeamOnboardingPanel" },
  "github/github": { panelId: "github", tabId: "github", label: "Remote", load: () => import("../components/GitHubSyncPanel"), exportName: "GitHubSyncPanel" },
  "github/ghactions": { panelId: "github", tabId: "ghactions", label: "Actions", load: () => import("../components/GhActionsPanel") },
  "github/triage": { panelId: "github", tabId: "triage", label: "Triage", load: () => import("../components/TriagePanel"), exportName: "TriagePanel" },
};

/** Whether Settings may offer to move this tab to another panel. */
export function isMovableTab(key: string): boolean {
  return key in TAB_REGISTRY;
}
